apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 100Mi
  volumeName: pvc-741aae6f-f451-4d85-b67b-69a053e632ac
