apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  labels:
    app: dnsmasq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: dnsmasq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dnsmasq
        name: dnsmasq
    spec:
      hostNetwork: true
      containers:
        - name: dnsmasq
          image: nucio.nowhere:30038/dnsmasq:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 67
              name: client-udp
              protocol: UDP
          volumeMounts:
            - name: storage-local-path-pvc
              subPath: "dnsmasq/dnsmasq.conf"
              mountPath: "/etc/dnsmasq.conf"
            - name: storage-local-path-pvc
              subPath: "dnsmasq/dnsmasq.leases"
              mountPath: "/var/lib/misc/dnsmasq.leases"
      nodeSelector:
        cputype: arm
      volumes:
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
      dnsPolicy: "ClusterFirstWithHostNet"
      dnsConfig:
        nameservers:
          - 10.43.0.22
