apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq
data:
  dnsmasq.conf: |
    # Set the interface on which dnsmasq operates.
    # If not set, all the interfaces is used.
    #interface=eth0

    # To disable dnsmasq's DNS server functionality.
    #port=0

    # listen to every interface
    except-interface=none

    # To enable dnsmasq's DHCP server functionality.
    dhcp-range=192.168.2.10,192.168.2.199,255.255.255.0,12h
    #dhcp-range=192.168.0.50,192.168.0.150,12h

    # Set gateway as Router. Following two lines are identical.
    #dhcp-option=option:router,192.168.0.1
    dhcp-option=3,192.168.2.1

    # Set DNS server as Router.
    dhcp-option=6,192.168.2.201

    # dhcp v4 rapid commit
    dhcp-rapid-commit

    domain-needed
    bogus-priv
    expand-hosts
    no-resolv

    # domain setup
    domain=nowhere
    local=/nowhere/

    dhcp-authoritative

    #server=1.1.1.1

    # Logging.
    log-async
    log-queries # log queries.
    log-dhcp    # log dhcp related messages.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  labels:
    app: dnsmasq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: dnsmasq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dnsmasq
        name: dnsmasq
    spec:
      hostNetwork: true
      containers:
        - name: dnsmasq
          image: nucio.nowhere:30038/dnsmasq:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 67
              name: client-udp
              protocol: UDP
          volumeMounts:
            - name: confmap-vol
              subPath: "dnsmasq.conf"
              mountPath: "/etc/dnsmasq.conf"
            - name: storage-local-path-pvc
              subPath: "dnsmasq/dnsmasq.leases"
              mountPath: "/var/lib/misc/dnsmasq.leases"
      nodeSelector:
        cputype: arm
      volumes:
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
        - configMap:
            name: dnsmasq
          name: confmap-vol
      dnsPolicy: "ClusterFirstWithHostNet"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq-ui
  labels:
    app: dnsmasq-ui
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: dnsmasq-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dnsmasq-ui
        name: dnsmasq-ui
    spec:
      containers:
        - name: dnsmasq-ui
          image: nucio.nowhere:30038/dnsmasq-ui:latest
          imagePullPolicy: Always
          command: ["/bin/sleep", "3650d"]
          volumeMounts:
            - name: storage-local-path-pvc
              subPath: "dnsmasq/dnsmasq.leases"
              mountPath: "/var/lib/misc/dnsmasq.leases"
      nodeSelector:
        cputype: arm
      volumes:
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-ui
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: dnsmasq-ui-svc
    metallb.universe.tf/loadBalancerIPs: 192.168.2.208
spec:
  externalTrafficPolicy: Local
  selector:
    app: dnsmasq-ui
  ports:
    - port: 80
      targetPort: 8989
  type: LoadBalancer
