apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq
data:
  dnsmasq.conf: |
    # Set the interface on which dnsmasq operates.
    # If not set, all the interfaces is used.
    # interface=eno1

    # To disable dnsmasq's DNS server functionality.
    #port=0

    # listen to every interface
    except-interface=none

    # IPV6
    # dhcp-range=::100,::1fff,constructor:eno1,ra-stateless,ra-names,slaac
    # enable-ra

    # To enable dnsmasq's DHCP server functionality.
    dhcp-range=192.168.2.10,192.168.2.199,255.255.255.0,1d

    dhcp-host=B4:75:0E:72:00:F5,192.168.2.10,wemo1,1d
    dhcp-host=94:10:3E:69:D1:2D,192.168.2.11,wemo2,1d
    dhcp-host=B4:75:0E:72:02:C5,192.168.2.12,wemo3,1d

    dhcp-host=E4:FA:C4:19:09:64,192.168.2.13,tapo1,1d
    dhcp-host=E4:FA:C4:19:0E:46,192.168.2.14,tapo2,1d
    dhcp-host=E4:FA:C4:19:0E:4C,192.168.2.15,tapo3,1d

    dhcp-host=48:B0:2D:4F:77:6B,192.168.2.16,shield,1d
    dhcp-host=DC:68:EB:10:78:77,192.168.2.17,switch,1d
    dhcp-host=BC:97:40:03:91:77,192.168.2.18,solar-panels,1d
    dhcp-host=98:E2:55:82:CD:14,192.168.2.19,switch2,1d
    dhcp-host=98:E2:55:F1:68:2B,192.168.2.20,switch2-docked,1d

    # Set gateway as Router. Following two lines are identical.
    dhcp-option=3,192.168.2.1

    # Set DNS server as PiHole
    dhcp-option=6,192.168.2.201,192.168.2.202

    # dhcp v4 rapid commit
    dhcp-rapid-commit

    domain-needed
    bogus-priv
    expand-hosts
    no-resolv

    # domain setup
    domain=nowhere
    local=/nowhere/

    dhcp-authoritative

    # Logging.
    log-async
    log-queries # log queries.
    log-dhcp    # log dhcp related messages.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: dnsmasq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dnsmasq
        part-of: dnsmasq
    spec:
      hostNetwork: true
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "part-of"
                    operator: In
                    values:
                      - dnsmasq
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: dnsmasq
          image: nucio.nowhere:30038/dnsmasq:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: TZ
              value: "Europe/Dublin"
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 67
              name: client-udp
              protocol: UDP
          startupProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: confmap-vol
              subPath: "dnsmasq.conf"
              mountPath: "/etc/dnsmasq.conf"
            - name: dnsmasq-pvc
              mountPath: "/var/lib/misc/"
          resources:
            limits:
              cpu: 20m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
      volumes:
        - name: dnsmasq-pvc
          persistentVolumeClaim:
            claimName: dnsmasq-pvc
        - configMap:
            name: dnsmasq
          name: confmap-vol
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-internal
spec:
  clusterIP: 10.43.0.23
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: port53
    - port: 67
      targetPort: 67
      protocol: UDP
      name: port67
  selector:
    app: dnsmasq
  type: ClusterIP
