apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq-ui
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: dnsmasq-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dnsmasq-ui
        part-of: dnsmasq
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "part-of"
                    operator: In
                    values:
                      - dnsmasq
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: dnsmasq-ui
          image: nucio.nowhere:30038/dnsmasq-ui:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "Europe/Dublin"
          volumeMounts:
            - name: dnsmasq-pvc
              mountPath: "/var/lib/misc/"
          ports:
            - containerPort: 5000
              name: dnsmasq-ui-tcp
              protocol: TCP
          startupProbe:
            httpGet:
              path: /healthz
              port: dnsmasq-ui-tcp
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: dnsmasq-ui-tcp
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: dnsmasq-ui-tcp
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 30m
              memory: 30Mi
            requests:
              cpu: 10m
              memory: 10Mi
      volumes:
        - name: dnsmasq-pvc
          persistentVolumeClaim:
            claimName: dnsmasq-pvc
      dnsPolicy: "ClusterFirstWithHostNet"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-ui
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.208
spec:
  externalTrafficPolicy: Local
  selector:
    app: dnsmasq-ui
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
