apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      volumes:
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
        - name: nasio-nfs-pvc
          persistentVolumeClaim:
            claimName: nasio-nfs-pvc
      containers:
        - image: jellyfin/jellyfin:latest
          imagePullPolicy: Always
          name: jellyfin
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/config"
              subPath: "jellyfin-config"
              name: storage-local-path-pvc
            - mountPath: "/cache"
              subPath: "jellyfin-cache"
              name: storage-local-path-pvc
            - mountPath: "/data"
              name: nasio-nfs-pvc
          ports:
            - containerPort: 8096
              name: http-tcp
              protocol: TCP
            - containerPort: 8920
              name: https-tcp
              protocol: TCP
            - containerPort: 1900
              name: dlna-udp
              protocol: UDP
            - containerPort: 7359
              name: discovery-udp
              protocol: UDP
      nodeSelector:
        cputype: x86
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-tcp
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: jellyfin-svc
    metallb.universe.tf/loadBalancerIPs: 192.168.2.210
spec:
  externalTrafficPolicy: Local
  selector:
    app: jellyfin
  ports:
    - port: 8096 # < port to open on the outside on the server
      targetPort: 8096 # < targetport. port on the pod to passthrough
      name: http-tcp # < reference name for the port in the deployment yaml
      protocol: TCP
    - port: 8920
      targetPort: 8920
      name: https-tcp
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-udp
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: jellyfin-svc
    metallb.universe.tf/loadBalancerIPs: 192.168.2.210
spec:
  externalTrafficPolicy: Local
  selector:
    app: jellyfin
  ports:
    - port: 1900
      targetPort: 1900
      name: dlna-udp
      protocol: UDP
    - port: 7359
      targetPort: 7359
      name: discovery-udp
      protocol: UDP
  type: LoadBalancer
