apiVersion: v1
kind: Service
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: longhorn-svc
    metallb.universe.tf/loadBalancerIPs: 192.168.2.214
spec:
  externalTrafficPolicy: Local
  selector:
    app: longhorn-ui
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: http
  type: LoadBalancer
