apiVersion: v1
kind: Service
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.214
    external-dns.alpha.kubernetes.io/hostname: longhorn.nowhere
spec:
  externalTrafficPolicy: Local
  selector:
    app: longhorn-ui
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: http
  type: LoadBalancer
