apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: http://192.168.2.215
  dex.config: |
    connectors:
    - config:
        issuer: http://192.168.2.221:9000/application/o/argocd/
        clientID: LhRF42giAPt8yhbHKJYWZeQdqeF6NgJvRSZUtyoJ
        clientSecret: $dex.authentik.clientSecret
        insecureEnableGroups: true
        insecureSkipVerify: true
        scopes:
          - openid
          - profile
          - email
          - groups
        name: authentik
        type: oidc
        id: authentik
