apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-authentik
          image: curlimages/curl:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo "Waiting for Authentik to be ready..."
              until curl -f -s http://192.168.2.221:9000/application/o/argocd/.well-known/openid-configuration > /dev/null; do
                echo "Authentik not ready, waiting 10 seconds..."
                sleep 10
              done
              echo "Authentik is ready!"
