apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, *, *, *, allow
    g, ArgoCD Admins, role:admin
  policy.default: "role:readonly"
