apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k3dvol/qbittorrent"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-nfs-pv-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
    - rsize=4096
    - wsize=4096
    - noacl
    - nocto
    - noatime
    - nodiratime
  nfs:
    path: "/volume1/public/Torrent Downloads"
    server: 192.168.2.3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-nfs-pv-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbitorrent-nordvpn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: qbitorrent-nordvpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbitorrent-nordvpn
    spec:
      volumes:
        - name: qbittorrent-storage
          persistentVolumeClaim:
            claimName: qbittorrent-pv-claim
        - name: torrent-nfs
          persistentVolumeClaim:
            claimName: torrent-nfs-pv-claim
      containers:
        - image: nucio.nowhere:30038/nordvpn:latest
          imagePullPolicy: Always
          name: nordvpn
          lifecycle:
            postStart:
              exec:
                command:
                  ["/bin/sh", "-c", "/wait_for_nordvpn.sh > /usr/share/message"]
          env:
            - name: NORDVPN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nordvpn-token
                  key: password
            - name: COUNTRY
              value: "P2P"
            - name: NETWORK
              value: "192.168.2.0/24"
            - name: PORTS
              value: "8112"
            - name: DNS
              value: "192.168.2.201"
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
        - image: linuxserver/qbittorrent:latest
          imagePullPolicy: Always
          name: deluge
          ports:
            - containerPort: 8112
              protocol: TCP
            - containerPort: 58846
              protocol: TCP
            - containerPort: 6881
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
          volumeMounts:
            - mountPath: "/config"
              name: qbittorrent-storage
            - mountPath: "/volume1/public/Torrent Downloads"
              name: torrent-nfs
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
            - name: WEBUI_PORT
              value: "8112"
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.2.201
---
apiVersion: v1
kind: Service
metadata:
  name: qbitorrent-nordvpn
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: qbitorrent-nordvpn-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.207
  selector:
    app: qbitorrent-nordvpn
  ports:
    - port: 8112
      targetPort: 8112
      name: qbitorrent-web
  type: LoadBalancer
