apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k3dvol/sonarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-nfs-pv-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
    - rsize=4096
    - wsize=4096
    - noacl
    - nocto
    - noatime
    - nodiratime
  nfs:
    path: /volume1/public
    server: 192.168.2.3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-nfs-pv-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
        - name: sonarr-storage
          persistentVolumeClaim:
            claimName: sonarr-pv-claim
        - name: sonarr-nfs
          persistentVolumeClaim:
            claimName: sonarr-nfs-pv-claim
      containers:
        - image: lscr.io/linuxserver/sonarr:latest
          imagePullPolicy: Always
          name: sonarr
          volumeMounts:
            - mountPath: "/config"
              name: sonarr-storage
            - mountPath: "/volume1/public"
              name: sonarr-nfs
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.2.201
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: sonarr-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.203
  selector:
    app: sonarr
  ports:
    - port: 80
      targetPort: 8989
  type: LoadBalancer
