apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
        - name: sonarr-pvc
          persistentVolumeClaim:
            claimName: sonarr-pvc
        - name: nasio-nfs-pvc
          persistentVolumeClaim:
            claimName: nasio-nfs-pvc
      containers:
        - image: linuxserver/sonarr:latest
          imagePullPolicy: Always
          name: sonarr
          volumeMounts:
            - mountPath: "/config"
              name: sonarr-pvc
            - mountPath: "/volume1/public"
              name: nasio-nfs-pvc
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
          startupProbe:
            httpGet:
              path: /
              port: 8989
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8989
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8989
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            limits:
              cpu: 200m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: default
spec:
  selector:
    app: sonarr
  ports:
    - port: 80
      targetPort: 8989
      protocol: TCP
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-tls
  namespace: default
spec:
  secretName: sonarr-tls
  issuerRef:
    name: blinky-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - sonarr.nowhere
  privateKey:
    rotationPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.alpha.kubernetes.io/hostname: sonarr.nowhere
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - sonarr.nowhere
      secretName: sonarr-tls
  rules:
    - host: sonarr.nowhere
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 80
