apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
        - name: sonarr-storage
          persistentVolumeClaim:
            claimName: config-pv-claim
        - name: sonarr-nfs
          persistentVolumeClaim:
            claimName: nfs-pv-claim
      containers:
        - image: linuxserver/sonarr:latest
          imagePullPolicy: Always
          name: sonarr
          volumeMounts:
            - mountPath: "/config"
              subPath: "sonarr"
              name: sonarr-storage
            - mountPath: "/volume1/public"
              name: sonarr-nfs
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.2.201
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: sonarr-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.203
  selector:
    app: sonarr
  ports:
    - port: 80
      targetPort: 8989
  type: LoadBalancer
