apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssh-server-storage-local-path-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/storage/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssh-server-storage-local-path-pvc
  namespace: default
spec:
  storageClassName: local-path
  volumeName: ssh-server-storage-local-path-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ssh-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ssh-server
    spec:
      volumes:
        - name: ssh-server-storage-local-path-pvc
          persistentVolumeClaim:
            claimName: ssh-server-storage-local-path-pvc
      containers:
        - image: lscr.io/linuxserver/openssh-server:latest
          ports:
            - containerPort: 2222
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "EU/Dublin"
            - name: USER_NAME
              value: "admin"
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: sshpassword
            - name: PASSWORD_ACCESS
              value: "true"
            - name: SUDO_ACCESS
              value: "true"          
          name: ssh-server
          volumeMounts:
            - mountPath: "/storage"
              name: ssh-server-storage-local-path-pvc
      nodeSelector:
        cputype: arm
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-server
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: ssh-server-svc
    metallb.universe.tf/loadBalancerIPs: 192.168.2.209
spec:
  externalTrafficPolicy: Local
  selector:
    app: ssh-server
  ports:
    - port: 2222
  type: LoadBalancer
