apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile-yvonne
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: seafile-yvonne
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seafile-yvonne
    spec:
      volumes:
        - name: seafile-yvonne-pvc
          persistentVolumeClaim:
            claimName: seafile-yvonne-pvc
      containers:
        - name: mariadb
          image: mariadb:12.0.2
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "db_dev"
            - name: MARIADB_AUTO_UPGRADE
              value: "true"
            - name: MARIADB_DATABASE
              value: "seafile"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: seafile-yvonne-pvc
              subPath: "mariadb"
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - mariadb-admin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -pdb_dev
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - mariadb-admin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -pdb_dev
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
        - name: memcached
          image: memcached:1.6.18
          args: ["-m", "256"]
          ports:
            - containerPort: 11211
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
        - name: seafile
          image: seafileltd/seafile-mc:12.0-latest
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_ROOT_PASSWD
              value: "db_dev"
            - name: DB_USER
              value: "root"
            - name: DB_USER_PASSWD
              value: "db_dev"
            - name: SEAFILE_LOG_TO_STDOUT
              value: "true"
            - name: TIME_ZONE
              value: "Europe/Dublin"
            - name: SEAFILE_ADMIN_EMAIL
              value: "admin@seafile.com"
            - name: SEAFILE_ADMIN_PASSWORD
              value: "admin_password"
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "false"
            - name: SEAFILE_SERVER_HOSTNAME
              value: "192.168.2.223"
            - name: SEAFILE_SERVER_PROTOCOL
              value: "http"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: seafile-yvonne-pvc
              subPath: "seafile"
              mountPath: /shared
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 30
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: seafile-yvonne
  namespace: default
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.223
spec:
  externalTrafficPolicy: Local
  selector:
    app: seafile-yvonne
  ports:
    - port: 80
      targetPort: 80
      name: seafile-ui
      protocol: TCP
  type: LoadBalancer