apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-yvonne-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 1Gi
  #volumeName: pvc-a5fdec61-a9df-46ee-aded-169ec5ec6994
