apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    app: docker-registry
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: storage-local-path-pvc
              mountPath: /data
              subPath: "registry"
          env:
            - name: REGISTRY_HTTP_ADDR
              value: :5000
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /data
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      nodeSelector:
        cputype: x86
      volumes:
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  labels:
    run: docker-registry
  namespace: kube-system
spec:
  selector:
    app: docker-registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30038
  type: NodePort
