apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:mantic
          imagePullPolicy: Always
          command: ["/bin/sleep", "3650d"]
          securityContext:
            privileged: true
      nodeSelector:
        cputype: x86
      restartPolicy: Always
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
