apiVersion: v1
kind: Pod
metadata:
  name: docker-builder
  labels:
    app: docker-builder
spec:
  containers:
    - name: docker-builder
      image: nucio.nowhere:30038/docker-builder:latest
      imagePullPolicy: Always
      securityContext:
        privileged: true
      command: ["/bin/sleep", "3650d"]
  restartPolicy: Always
