apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          imagePullPolicy: Always
          command: ["/bin/sleep", "3650d"]
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
      nodeSelector:
        cputype: arm
      restartPolicy: Always
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.2.201
