apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      imagePullPolicy: Always
      command: ["/bin/sleep", "3650d"]
      securityContext:
        privileged: true
  restartPolicy: Always
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 192.168.2.201
