apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  volumes:
    - name: storage-local-path-pvc
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: ubuntu
      image: ubuntu:latest
      imagePullPolicy: Always
      command: ["/bin/sleep", "3650d"]
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: "/opt/test2"
          name: storage-local-path-pvc
  nodeSelector:
    cputype: x86
  restartPolicy: Always
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 192.168.2.201
