apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-nordvpn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: debug-nordvpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: debug-nordvpn
        part-of: debug-nordvpn
    spec:
      containers:
        - image: nucio.nowhere:30038/nordvpn:latest
          imagePullPolicy: Always
          name: nordvpn
          lifecycle:
            postStart:
              exec:
                command:
                  ["/bin/sh", "-c", "/wait_for_nordvpn.sh > /usr/share/message"]
          env:
            - name: NORDVPN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nordvpn-token
                  key: password
            - name: COUNTRY
              value: "P2P"
            - name: NETWORK
              value: "192.168.2.0/24;10.42.0.0/16;10.43.0.0/16"
            - name: PORTS
              value: "8112,6881,9696,8080,53"
            - name: DNS
              value: "10.43.0.22"
            - name: MESHNET
              value: "True"
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
