apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      volumes:
        - name: ubuntu-pvc
          persistentVolumeClaim:
            claimName: ubuntu-pvc
      containers:
        - name: ubuntu
          image: ubuntu:oracular
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: ubuntu-pvc
              mountPath: /root
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
