apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      imagePullPolicy: Always
      command: ["/bin/sleep", "3650d"]
  restartPolicy: Always
