# Use this pod to recover a corrupted Postgres database (e.g. after unclean shutdown).
#
# Steps:
#   kubectl apply -f ./postgres-recovery.yaml
#   kubectl exec -it postgres-recovery -- bash
#   su - postgres
#   cd /usr/lib/postgresql/16/bin/
#   ./pg_resetwal -f /var/lib/postgresql/data/
#
# When done: kubectl delete -f ./postgres-recovery.yaml
apiVersion: v1
kind: Pod
metadata:
  name: postgres-recovery
spec:
  containers:
    - name: postgres
      image: docker.io/library/postgres:16
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: postgres-data
          subPath: "postgresql"
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: paperless-pvc
