apiVersion: v1
kind: Pod
metadata:
  name: postgres-recovery
spec:
  containers:
    - name: postgres
      image: postgres:15-alpine
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: warracker-pvc
