apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleanuparr-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-7402cb82-aa06-4010-9bdf-f5b5e26453fa
