apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanuparr
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: cleanuparr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cleanuparr
    spec:
      volumes:
        - name: cleanuparr-pvc
          persistentVolumeClaim:
            claimName: cleanuparr-pvc
      containers:
        - image: ghcr.io/cleanuparr/cleanuparr:latest
          imagePullPolicy: Always
          name: cleanuparr
          volumeMounts:
            - mountPath: "/config"
              name: cleanuparr-pvc
          startupProbe:
            httpGet:
              path: /
              port: 11011
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 11011
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 11011
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            limits:
              cpu: 200m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cleanuparr
  namespace: default
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.206
spec:
  externalTrafficPolicy: Local
  selector:
    app: cleanuparr
  ports:
    - port: 80
      targetPort: 11011
  type: LoadBalancer
