apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr
data:
  settings.sh: |
    #!/bin/bash

    # hostname of the gateway - it must accept vxlan and DHCP traffic
    # clients get it as env variable
    GATEWAY_NAME="$gateway"
    # K8S DNS IP address
    # clients get it as env variable
    K8S_DNS_IPS="$K8S_DNS_ips"
    # Blank  sepated IPs not sent to the POD gateway but to the default K8S
    # This is needed, for example, in case your CNI does
    # not add a non-default rule for the K8S addresses (Flannel does)
    NOT_ROUTED_TO_GATEWAY_CIDRS="10.0.0.0/8 192.168.2.0/24"

    # Vxlan ID to use
    VXLAN_ID="42"
    # VXLAN need an /24 IP range not conflicting with K8S and local IP ranges
    VXLAN_IP_NETWORK="172.16.0"
    # Keep a range of IPs for static assignment in nat.conf
    VXLAN_GATEWAY_FIRST_DYNAMIC_IP=20

    # ICMP heartbeats are used to ensure the pod-gateway is connectable from the clients.
    # The following value can be used to to provide more stability in an unreliable network connection.
    CONNECTION_RETRY_COUNT=1

  nat.conf: |
    # Configure client PODs with static IP addresses
    # and ports exposed through NAT
    # static IPs must be bellow VXLAN_GATEWAY_FIRST_DYNAMIC_IP
    #
    # hostname IP ports(coma separated)
    # Example:
    # transmission 10 tcp:18289,udp:18289
    prowlarr 11 tcp:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
        part-of: nordvpn
    spec:
      hostname: prowlarr
      volumes:
        - name: confmap-vol
          configMap:
            name: prowlarr
        - name: prowlarr-pvc
          persistentVolumeClaim:
            claimName: prowlarr-pvc
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "part-of"
                    operator: In
                    values:
                      - nordvpn
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: linuxserver/prowlarr:latest
          imagePullPolicy: Always
          name: prowlarr
          volumeMounts:
            - mountPath: "/config"
              name: prowlarr-pvc
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
          readinessProbe:
            httpGet:
              path: /system/status/
              port: 9696
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /system/status/
              port: 9696
            initialDelaySeconds: 10
            timeoutSeconds: 10
        - image: nucio.nowhere:30038/pod-gateway:latest
          imagePullPolicy: Always
          name: pod-gateway
          command: ["/bin/client_sidecar.sh"]
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: "/config"
              name: confmap-vol
      initContainers:
        - image: nucio.nowhere:30038/pod-gateway:latest
          imagePullPolicy: Always
          name: pod-gateway-init
          command: ["/bin/client_init.sh"]
          env:
            - name: gateway
              value: "nordvpn.default.svc.cluster.local"
            - name: K8S_DNS_ips
              value: "10.43.0.10"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/config"
              name: confmap-vol
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/loadBalancerIPs: 192.168.2.207
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: prowlarr
  ports:
    - port: 80
      targetPort: 9696
      name: prowlarr-web
  type: LoadBalancer
