apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      volumes:
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
      containers:
        - image: linuxserver/prowlarr:latest
          imagePullPolicy: Always
          name: prowlarr
          volumeMounts:
            - mountPath: "/config"
              subPath: "prowlarr"
              name: storage-local-path-pvc
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      nodeSelector:
        cputype: x86
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.2.201
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: prowlarr-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.208
  selector:
    app: prowlarr
  ports:
    - port: 80
      targetPort: 9696
  type: LoadBalancer
