apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: tdarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tdarr
      annotations:
        diun.enable: "true"
    spec:
      volumes:
        - name: tdarr-config
          persistentVolumeClaim:
            claimName: config-pv-claim
        - name: tdarr-nfs
          persistentVolumeClaim:
            claimName: nfs-pv-claim
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - image: haveagitgat/tdarr:latest
          imagePullPolicy: Always
          name: tdarr
          resources:
            limits:
              gpu.intel.com/i915: 1
          env:
            - name: TZ
              value: "EU/Dublin"
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: internalNode
              value: "true"
            - name: nodeID
              value: "internal"
          ports:
            - containerPort: 8265
              name: ui
            - containerPort: 8266
              name: server
          volumeMounts:        
            - mountPath: /app/configs
              subPath: "tdarr/config"
              name: tdarr-config
            - mountPath: /app/server
              subPath: "tdarr/server"
              name: tdarr-config
            - mountPath: /app/logs
              subPath: "tdarr/logs"
              name: tdarr-config
            - mountPath: /nasio
              name: tdarr-nfs
            - mountPath: /dev/shm
              name: dshm
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.2.201
---
apiVersion: v1
kind: Service
metadata:
  name: tdarr
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: tdarr-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.209
  selector:
    app: tdarr
  ports:
    - port: 8265
      targetPort: 8265
      name: tdarr-ui
      protocol: TCP
    - port: 8266
      targetPort: 8266
      name: tdarr-serverx
      protocol: TCP
  type: LoadBalancer
