apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mealie
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mealie
    spec:
      volumes:
        - name: mealie-pvc
          persistentVolumeClaim:
            claimName: mealie-pvc
      containers:
        - image: postgres:15
          imagePullPolicy: Always
          name: postgres
          env:
            - name: POSTGRES_USER
              value: "mealie"
            - name: POSTGRES_PASSWORD
              value: "mealie"
            - name: POSTGRES_DB
              value: "mealie"
            - name: PGUSER
              value: "mealie"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              subPath: "postgresql_15"
              name: mealie-pvc
          startupProbe:
            exec:
              command:
                - pg_isready
                - -U
                - mealie
                - -d
                - mealie
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - mealie
                - -d
                - mealie
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - mealie
                - -d
                - mealie
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 100Mi
        - image: ghcr.io/mealie-recipes/mealie:latest
          imagePullPolicy: Always
          name: mealie
          volumeMounts:
            - mountPath: "/app/data"
              subPath: "mealie/data"
              name: mealie-pvc
          ports:
            - containerPort: 9000
              name: mealie-tcp
              protocol: TCP
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Anchorage"
            - name: BASE_URL
              value: "https://mealie.yourdomain.com"
            - name: DB_ENGINE
              value: "postgres"
            - name: POSTGRES_USER
              value: "mealie"
            - name: POSTGRES_PASSWORD
              value: "mealie"
            - name: POSTGRES_SERVER
              value: "localhost"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "mealie"
          startupProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 300Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: default
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.223
spec:
  externalTrafficPolicy: Local
  selector:
    app: mealie
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  type: LoadBalancer
