apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mealie
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mealie
    spec:
      volumes:
        - name: mealie-pvc
          persistentVolumeClaim:
            claimName: mealie-pvc
      containers:
        - image: postgres:15
          imagePullPolicy: Always
          name: postgres
          env:
            - name: POSTGRES_USER
              value: "mealie"
            - name: POSTGRES_PASSWORD
              value: "mealie"
            - name: POSTGRES_DB
              value: "mealie"
            - name: PGUSER
              value: "mealie"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              subPath: "postgresql_15"
              name: mealie-pvc
          startupProbe:
            exec:
              command:
                - pg_isready
                - -U
                - mealie
                - -d
                - mealie
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - mealie
                - -d
                - mealie
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - mealie
                - -d
                - mealie
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 100Mi
        - image: ghcr.io/mealie-recipes/mealie:latest
          imagePullPolicy: Always
          name: mealie
          volumeMounts:
            - mountPath: "/app/data"
              subPath: "mealie/data"
              name: mealie-pvc
          ports:
            - containerPort: 9000
              name: mealie-tcp
              protocol: TCP
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Dublin"
            - name: BASE_URL
              value: "https://mealie.nowhere"
            - name: DB_ENGINE
              value: "postgres"
            - name: POSTGRES_USER
              value: "mealie"
            - name: POSTGRES_PASSWORD
              value: "mealie"
            - name: POSTGRES_SERVER
              value: "localhost"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "mealie"
            - name: OIDC_AUTH_ENABLED
              value: "true"
            - name: OIDC_PROVIDER_NAME
              value: "authentik"
            - name: OIDC_CONFIGURATION_URL
              value: "http://192.168.2.221:9000/application/o/mealie/.well-known/openid-configuration"
            - name: OIDC_CLIENT_ID
              value: "Pi4EqaksAIldJt49JG5chHpT3KWvMJt3Vg62WoDl"
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: oidc_secret
                  name: mealie
            - name: OIDC_SIGNUP_ENABLED
              value: "true"
            - name: OIDC_USER_GROUP
              value: "Regular Users"
            - name: OIDC_ADMIN_GROUP
              value: "Blinky Admins"
            - name: OIDC_REMEMBER_ME
              value: "true"
          startupProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 300Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: default
spec:
  selector:
    app: mealie
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-tls
  namespace: default
spec:
  secretName: mealie-tls
  issuerRef:
    name: blinky-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - mealie.nowhere
  privateKey:
    rotationPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.alpha.kubernetes.io/hostname: mealie.nowhere
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mealie.nowhere
      secretName: mealie-tls
  rules:
    - host: mealie.nowhere
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mealie
                port:
                  number: 80
