apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-3ae84376-eddc-4c16-865e-772d1319e679
