network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 192.168.2.3/24
      routes:
        - to: default
          via: 192.168.2.1
      nameservers:
        addresses: [1.1.1.1, 1.0.0.1]
      match:
        macaddress: b8:27:eb:85:e5:1b
      set-name: eth0
