apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: heimdall
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      volumes:
        - name: heimdall-pvc
          persistentVolumeClaim:
            claimName: heimdall-pvc
      containers:
        - image: linuxserver/heimdall:latest
          imagePullPolicy: Always
          name: heimdall
          volumeMounts:
            - mountPath: "/config"
              name: heimdall-pvc
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
          ports:
            - containerPort: 80
              name: http-80
              protocol: TCP
            - containerPort: 443
              name: https-443
              protocol: TCP
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/loadBalancerIPs: 192.168.2.200
spec:
  externalTrafficPolicy: Local
  selector:
    app: heimdall
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https-443
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
