apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nordvpn-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 100Mi
  volumeName: pvc-0fde914b-bf62-494b-9084-b7404fa29264
