apiVersion: apps/v1
kind: Deployment
metadata:
  name: nordvpn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nordvpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nordvpn
    spec:
      containers:
        - image: nucio.nowhere:30038/nordvpn:latest
          imagePullPolicy: Always
          name: nordvpn
          env:
            - name: NORDVPN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nordvpn-token
                  key: password
            - name: COUNTRY
              value: "Ireland"
            - name: NETWORK
              value: "192.168.2.0/24"
            - name: PORTS
              value: "8080,8112,6881"
            - name: DNS
              value: "10.43.0.22"
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
