apiVersion: apps/v1
kind: Deployment
metadata:
  name: nordvpn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nordvpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nordvpn
        part-of: nordvpn
    spec:
      volumes:
        - name: nordvpn-pvc
          persistentVolumeClaim:
            claimName: nordvpn-pvc
        - name: prowlarr-pvc
          persistentVolumeClaim:
            claimName: prowlarr-pvc
        - name: qbittorrent-pvc
          persistentVolumeClaim:
            claimName: qbittorrent-pvc
        - name: nasio-nfs-pvc
          persistentVolumeClaim:
            claimName: nasio-nfs-pvc
      containers:
        - image: nucio.nowhere:30038/nordvpn:latest
          imagePullPolicy: Always
          name: nordvpn
          volumeMounts:
            - mountPath: "/config"
              name: nordvpn-pvc
          lifecycle:
            postStart:
              exec:
                command:
                  ["/bin/sh", "-c", "/wait_for_nordvpn.sh > /usr/share/message"]
          env:
            - name: NORDVPN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nordvpn-token
                  key: password
            - name: COUNTRY
              value: "P2P"
            - name: NETWORK
              value: "192.168.2.0/24;10.43.0.0/16"
            - name: PORTS
              value: "8112,6881,9696,8080"
            - name: DNS
              value: "192.168.2.201"
            - name: MESHNET
              value: "True"
          livenessProbe:
            exec:
              command:
                - /check_nordvpn_connection.sh
            initialDelaySeconds: 30
            periodSeconds: 600
            timeoutSeconds: 30
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 150Mi
        - image: linuxserver/prowlarr:latest
          imagePullPolicy: Always
          name: prowlarr
          volumeMounts:
            - mountPath: "/config"
              name: prowlarr-pvc
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
          readinessProbe:
            httpGet:
              path: /system/status/
              port: 9696
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /system/status/
              port: 9696
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 200m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 50Mi
        - image: linuxserver/qbittorrent:latest
          imagePullPolicy: Always
          name: qbittorrent
          ports:
            - containerPort: 8112
              protocol: TCP
            - containerPort: 6881
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
          volumeMounts:
            - mountPath: "/config"
              name: qbittorrent-pvc
            - mountPath: "/volume1/public/Torrent Downloads"
              subPath: "Torrent Downloads"
              name: nasio-nfs-pvc
          readinessProbe:
            httpGet:
              path: /
              port: 8112
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8112
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
            - name: WEBUI_PORT
              value: "8112"
          resources:
            limits:
              cpu: 800m
              memory: 3000Mi
            requests:
              cpu: 100m
              memory: 100Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: nordvpn
spec:
  clusterIP: None
  ports:
    - port: 4789
      name: nordvpn-http
      protocol: UDP
  selector:
    app: nordvpn
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/loadBalancerIPs: 192.168.2.207
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: nordvpn
  ports:
    - port: 80
      targetPort: 9696
      name: prowlarr-web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/loadBalancerIPs: 192.168.2.209
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: nordvpn
  ports:
    - port: 8112
      targetPort: 8112
      name: qbittorrent-web
  type: LoadBalancer
