apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: registry-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - image: joxit/docker-registry-ui
          imagePullPolicy: Always
          name: registry-ui
          env:
            - name: SINGLE_REGISTRY
              value: "true"
            - name: NGINX_PROXY_PASS_URL
              value: "http://nucio.nowhere:30038"
            - name: DELETE_IMAGES
              value: "true"
      nodeSelector:
        cputype: x86
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: registry-ui-svc
    metallb.universe.tf/loadBalancerIPs: 192.168.2.214
spec:
  externalTrafficPolicy: Local
  selector:
    app: registry-ui
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
