apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-1b39e25e-ae03-4a8f-985a-fb883f0030a3
