apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
      annotations:
        diun.enable: "true"
    spec:
      volumes:
        - name: plex-storage
          persistentVolumeClaim:
            claimName: config-pv-claim
        - name: plex-nfs
          persistentVolumeClaim:
            claimName: nfs-pv-claim
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - image: plexinc/pms-docker:latest
          imagePullPolicy: Always
          name: plex
          resources:
            limits:
              gpu.intel.com/i915: 1
          volumeMounts:
            - mountPath: "/config"
              subPath: "plex"
              name: plex-storage
            - mountPath: "/data"
              name: plex-nfs
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: PLEX_UID
              value: "1026"
            - name: PLEX_GID
              value: "100"
            - name: ADVERTISE_IP
              value: "http://192.168.2.204:32400"
            - name: ALLOWED_NETWORKS
              value: "192.168.2.0/24,10.42.0.0/24"
            - name: HOSTNAME
              value: "nucio.nowhere"
            - name: TZ
              value: "Europe/Dublin"
          ports:
            - containerPort: 32400
              name: pms-web
              protocol: TCP
            - containerPort: 32469
              name: dlna-tcp
              protocol: TCP
            - containerPort: 1900
              name: dlna-udp
              protocol: UDP
            - containerPort: 32410
              name: gdm-32410
              protocol: UDP
            - containerPort: 32412
              name: gdm-32412
              protocol: UDP
            - containerPort: 32413
              name: gdm-32413
              protocol: UDP
            - containerPort: 32414
              name: gdm-32414
              protocol: UDP
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.2.201
---
apiVersion: v1
kind: Service
metadata:
  name: plex-udp
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: plex-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.204
  selector:
    app: plex
  ports:
    - port: 1900
      targetPort: 1900
      name: dlna-udp
      protocol: UDP
    - port: 32410
      targetPort: 32410
      name: gdm-32410
      protocol: UDP
    - port: 32412
      targetPort: 32412
      name: gdm-32412
      protocol: UDP
    - port: 32413
      targetPort: 32413
      name: gdm-32413
      protocol: UDP
    - port: 32414
      targetPort: 32414
      name: gdm-32414
      protocol: UDP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: plex-tcp
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: plex-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.204
  selector:
    app: plex
  ports:
    - port: 32400
      targetPort: 32400
      name: pms-web
      protocol: TCP
    - port: 32469
      targetPort: 32469
      name: dlna-tcp
      protocol: TCP
  type: LoadBalancer
