kind: Deployment
apiVersion: apps/v1
metadata:
  name: headlamp
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      volumes:
        - name: kubeconfig-volume
          secret:
            secretName: kubeconfig
            items:
              - key: kubeconfig
                path: kubeconfig
      containers:
        - name: headlamp
          image: ghcr.io/headlamp-k8s/headlamp:latest
          imagePullPolicy: Always
          args:
            - "-plugins-dir=/headlamp/plugins"
          ports:
            - containerPort: 4466
          volumeMounts:
            - name: kubeconfig-volume
              mountPath: /home/headlamp/.config/Headlamp/kubeconfigs/config
              subPath: kubeconfig
              readOnly: true
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 4466
            initialDelaySeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 4466
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 4466
            initialDelaySeconds: 30
            timeoutSeconds: 30
      nodeSelector:
        "kubernetes.io/os": linux
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
kind: Service
apiVersion: v1
metadata:
  name: headlamp
  namespace: kube-system
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.223
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: 4466
  selector:
    k8s-app: headlamp
  type: LoadBalancer
