apiVersion: apps/v1
kind: Deployment
metadata:
  name: netalertx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: netalertx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: netalertx
    spec:
      volumes:
        - name: netalertx-pvc
          persistentVolumeClaim:
            claimName: netalertx-pvc
      hostNetwork: true
      containers:
        - image: jokobsk/netalertx:latest
          imagePullPolicy: Always
          name: netalertx
          env:
            - name: TZ
              value: "Europe/Dublin"
          ports:
            - containerPort: 20211
              name: netalertx-tcp
              protocol: TCP
          volumeMounts:
            - mountPath: "/app/config"
              subPath: "config"
              name: netalertx-pvc
            - mountPath: "/app/db"
              subPath: "db"
              name: netalertx-pvc
          startupProbe:
            httpGet:
              path: /
              port: 20211
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 20211
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 20211
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 250Mi
            requests:
              cpu: 250m
              memory: 100Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: netalertx
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.218
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: netalertx
  ports:
    - port: 80
      targetPort: 20211
  type: LoadBalancer
