apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-gateway
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pod-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pod-gateway
    spec:
      volumes:
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
      containers:
        - image: nucio.nowhere:30038/pod-gateway:latest
          imagePullPolicy: Always
          name: pod-gateway
          command: ["bin/gateway_sidecar.sh"]
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: "/config"
              subPath: "pod-gateway"
              name: storage-local-path-pvc
      initContainers:
        - image: nucio.nowhere:30038/pod-gateway:latest
          imagePullPolicy: Always
          name: pod-gateway-init
          command: ["/bin/gateway_init.sh"]
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/config"
              subPath: "pod-gateway"
              name: storage-local-path-pvc
      nodeSelector:
        cputype: x86
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: pod-gateway
spec:
  clusterIP: None
  ports:
    - port: 4789
      name: pod-gateway-http
      protocol: UDP
  selector:
    app: pod-gateway
  type: ClusterIP
