apiVersion: v1
kind: Service
metadata:
  name: prometheus-debug
  namespace: monitoring
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.254
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: web
      port: 9090
      targetPort: web
  selector:
    prometheus: prometheus
