apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml

patches:
- target:
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: /metadata/name
      value: monitoring