apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml
  - prometheus-rbac.yaml
  - prometheus.yaml
  - monitor-node-exporter.yaml
  - monitor-longhorn.yaml
  - monitor-kubelet.yaml
  - monitor-snmp.yaml

patches:
  - target:
      kind: Namespace
      name: default
    patch: |-
      - op: replace
        path: /metadata/name
        value: monitoring
