apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  image: quay.io/prometheus/prometheus:latest
  imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 2
  resources:
    limits:
      memory: "600Mi"
      cpu: "200m"
    requests:
      memory: "400Mi"
      cpu: "100m"
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - node-exporter
          - longhorn-prometheus-servicemonitor
          - kubelet
          - snmp-exporter
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: 10.43.0.20
  ports:
    - name: web
      port: 9090
      targetPort: web
  selector:
    prometheus: prometheus
  sessionAffinity: ClientIP
