apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
  namespace: default
data:
  server.yml: |
    # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
    base-url: http://192.168.2.220
    listen: ":80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ntfy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      volumes:
        - name: config
          configMap:
            name: ntfy
      containers:
        - name: ntfy
          image: binwiederhier/ntfy:latest
          imagePullPolicy: Always
          args: ["serve"]
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - containerPort: 80
              name: http
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: config
              mountPath: "/etc/ntfy"
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: default
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.220
    external-dns.alpha.kubernetes.io/hostname: ntfy.nowhere
spec:
  externalTrafficPolicy: Local
  selector:
    app: ntfy
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
