apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
  namespace: default
data:
  server.yml: |
    # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
    base-url: http://ntfy.default.svc.cluster.local
    listen: ":80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ntfy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      volumes:
        - name: config
          configMap:
            name: ntfy
      containers:
        - name: ntfy
          image: binwiederhier/ntfy:latest
          imagePullPolicy: Always
          args: ["serve"]
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - containerPort: 80
              name: http
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: config
              mountPath: "/etc/ntfy"
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: default
spec:
  selector:
    app: ntfy
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntfy-tls
  namespace: default
spec:
  secretName: ntfy-tls
  issuerRef:
    name: blinky-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - ntfy.nowhere
  privateKey:
    rotationPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.alpha.kubernetes.io/hostname: ntfy.nowhere
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ntfy.nowhere
      secretName: ntfy-tls
  rules:
    - host: ntfy.nowhere
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80
