apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound
  namespace: default
data:
  listening-port.conf: |
    server:
      port: 5335
      verbosity: 2
  dnssec.conf: |
    server:
      module-config: "iterator"
      harden-glue: no
      harden-dnssec-stripped: no
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
        part-of: pihole
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostname: pihole
      nodeSelector:
        kubernetes.io/hostname: nucio
      containers:
        - name: pihole
          image: pihole/pihole:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - "NET_ADMIN"
                - "NET_BIND_SERVICE"
                - "NET_RAW"
                - "SYS_NICE"
                - "CHOWN"
                - "SYS_TIME"
          ports:
            - containerPort: 80
              name: pihole-http
              protocol: TCP
            - containerPort: 53
              name: dns
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 443
              name: pihole-ssl
              protocol: TCP
            - containerPort: 67
              name: client-udp
              protocol: UDP
          env:
            - name: TZ
              value: "Europe/Dublin"
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pihole-webpassword
            - name: FTLCONF_dns_reply_host_IPv4
              value: '192.168.2.2'
            - name: FTLCONF_dns_reply_host_force4
              value: 'true'
          startupProbe:
            httpGet:
              path: /admin/login
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /admin/login
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /admin/login
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: pihole-pvc
              subPath: "pihole"
              mountPath: "/etc/pihole"
            - name: pihole-pvc
              subPath: "pihole-dnsmasq"
              mountPath: "/etc/dnsmasq.d"
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 100Mi
        - image: klutchell/unbound:latest
          imagePullPolicy: Always
          name: unbound
          volumeMounts:
            - name: confmap-vol
              subPath: "listening-port.conf"
              mountPath: "/etc/unbound/custom.conf.d/listening-port.conf"
            - name: confmap-vol
              subPath: "dnssec.conf"
              mountPath: "/etc/unbound/custom.conf.d/dnssec.conf"
          startupProbe:
            tcpSocket:
              port: 5335
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 5335
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 5335
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: pihole-pvc
          persistentVolumeClaim:
            claimName: pihole-pvc
        - configMap:
            name: unbound
          name: confmap-vol
