apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - containerPort: 80
              name: pihole-http
              protocol: TCP
            - containerPort: 53
              name: dns
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 443
              name: pihole-ssl
              protocol: TCP
            - containerPort: 67
              name: client-udp
              protocol: UDP
          env:
            - name: ServerIP
              value: 192.168.2.4
            - name: TZ
              value: "EU/Dublin"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pihole-webpassword
            - name: DNSMASQ_LISTENING
              value: "all"
          volumeMounts:
            - name: storage-local-path-pvc
              subPath: "pihole"
              mountPath: "/etc/pihole"
            - name: storage-local-path-pvc
              subPath: "pihole-dnsmasq"
              mountPath: "/etc/dnsmasq.d"
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
        - image: mvance/unbound-rpi:latest
          imagePullPolicy: Always
          name: unbound
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/opt/unbound/etc/unbound/"
              subPath: "unbound"
              name: storage-local-path-pvc
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
      nodeSelector:
        cputype: arm
      volumes:
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-external
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.201
  ports:
    # pihole use Ports to expose (53, 80, 67, 443), the bare minimum ports required for Pi-holes HTTP and DNS services
    - port: 80
      targetPort: 80
      name: port80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: port443
      protocol: TCP
    - port: 53
      targetPort: 53
      protocol: TCP
      name: port53
    - port: 53
      targetPort: 53
      protocol: UDP
      name: port53-udp
    - port: 67
      targetPort: 67
      protocol: UDP
      name: port67-udp
  selector:
    app: pihole
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-internal
spec:
  clusterIP: 10.43.0.22
  ports:
    # pihole use Ports to expose (53, 80, 67, 443), the bare minimum ports required for Pi-holes HTTP and DNS services
    - port: 80
      targetPort: 80
      name: port80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: port443
      protocol: TCP
    - port: 53
      targetPort: 53
      protocol: TCP
      name: port53
    - port: 53
      targetPort: 53
      protocol: UDP
      name: port53-udp
    - port: 67
      targetPort: 67
      protocol: UDP
      name: port67-udp
  selector:
    app: pihole
  type: ClusterIP
