apiVersion: batch/v1
kind: Job
metadata:
  name: build-dnsmasq-ui
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - image: nucio.nowhere:30038/docker-builder:latest
          name: build-dnsmasq-ui
          imagePullPolicy: Always
          command: ["./build.sh"]
          args: ["dnsmasq-ui", "linux/amd64"]
          securityContext:
            privileged: true
      restartPolicy: Never
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
