apiVersion: batch/v1
kind: Job
metadata:
  name: build-dnsmasq
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - image: nucio.nowhere:30038/docker-builder:latest
          name: build-dnsmasq
          imagePullPolicy: Always
          command: ["./build.sh"]
          args: ["dnsmasq", "linux/arm64"]
          securityContext:
            privileged: true
      nodeSelector:
        cputype: x86
      restartPolicy: Never
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
