apiVersion: batch/v1
kind: Job
metadata:
  name: build-first-docker-builder
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      volumes:
        - name: scripts-volume
          configMap:
            name: init-docker-builder-scripts
            defaultMode: 0777
      containers:
        - image: ubuntu:mantic
          name: build-first-docker-builder
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /scripts
              name: scripts-volume
          command:
            - /bin/sh
            - -c
            - |
              ls -lh /scripts
              /scripts/init_docker_builder_script.sh
          securityContext:
            privileged: true
      nodeSelector:
        cputype: x86
      restartPolicy: Never
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
---
apiVersion: v1
items:
  - apiVersion: v1
    data:
      init_docker_builder_script.sh: |
        apt-get update 
        apt-get -y dist-upgrade 

        apt-get install -y ca-certificates curl gnupg lsb-release

        mkdir -m 0755 -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

        apt-get update 

        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin git 

        (cd /opt/ ; git clone https://github.com/blablack/fawnarevagh-kube.git)

        cp /opt/fawnarevagh-kube/docker/docker-builder/buildkitd.toml /etc/buildkitd.toml

        export DOCKER_BUILDKIT=1

        dockerd&

        docker buildx create --use --config /etc/buildkitd.toml

        (
          cd /opt/fawnarevagh-kube/docker/docker-builder
          docker buildx build --platform linux/amd64 --push --tag nucio.nowhere:30038/docker-builder:latest .
        )
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: init-docker-builder-scripts
kind: List
metadata: {}
