apiVersion: batch/v1
kind: Job
metadata:
  name: build-gateway-admision-controller
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - image: nucio.nowhere:30038/docker-builder:latest
          name: build-docker-builder
          imagePullPolicy: Always
          command: ["./build.sh"]
          args: ["pod-gateway-admision-controller", "linux/amd64"]
      nodeSelector:
        cputype: x86
      restartPolicy: Never
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
