apiVersion: batch/v1
kind: Job
metadata:
  name: build-first-docker-builder
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - image: ubuntu:mantic
          name: build-first-docker-builder
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - wget -O - https://raw.githubusercontent.com/blablack/fawnarevagh-kube/main/docker/docker-builder/init_script.sh | bash
      nodeSelector:
        cputype: x86
      restartPolicy: Never
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
