apiVersion: batch/v1
kind: Job
metadata:
  name: build-fdnmasq-ui
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - image: ubuntu:mantic
          name: build-fdnmasq-ui
          imagePullPolicy: Always
          command: ["./build.sh"]
          args: ["dnsmasq-ui", "linux/arm64"]
          securityContext:
            privileged: true
      nodeSelector:
        cputype: x86
      restartPolicy: Never
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
