apiVersion: batch/v1
kind: Job
metadata:
  name: build-dnsmasq-ui
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      volumes:
        - name: scripts-volume
          configMap:
            name: init-docker-builder-scripts
            defaultMode: 0777
      containers:
        - image: nucio.nowhere:30038/docker-builder:latest
          name: build-dnsmasq-ui
          imagePullPolicy: Always
          command: ["./build.sh"]
          args: ["dnsmasq-ui", "linux/arm64"]
          securityContext:
            privileged: true
      nodeSelector:
        cputype: x86
      restartPolicy: Never
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
