{
 "title": "Home Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "range", "label": "Time Range", "query": "1m, 5m, 15m, 30m, 60m" }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[$range])) * 100) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime - Nucio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (node_time_seconds{instance=\"192.168.2.2:9100\",job=\"node-exporter\"} - node_boot_time_seconds{instance=\"192.168.2.2:9100\",job=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime - Quario",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (node_time_seconds{instance=\"192.168.2.3:9100\",job=\"node-exporter\"} - node_boot_time_seconds{instance=\"192.168.2.3:9100\",job=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Basic - Nucio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=\"192.168.2.2:9100\",job=\"node-exporter\"} - node_memory_MemFree_bytes{instance=\"192.168.2.2:9100\",job=\"node-exporter\"} - (node_memory_Cached_bytes{instance=\"192.168.2.2:9100\",job=\"node-exporter\"} + node_memory_Buffers_bytes{instance=\"192.168.2.2:9100\",job=\"node-exporter\"} + node_memory_SReclaimable_bytes{instance=\"192.168.2.2:9100\",job=\"node-exporter\"}))",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "avg(node_memory_Cached_bytes{instance=\"192.168.2.2:9100\",job=\"node-exporter\"} + node_memory_Buffers_bytes{instance=\"192.168.2.2:9100\",job=\"node-exporter\"} + node_memory_SReclaimable_bytes{instance=\"192.168.2.2:9100\",job=\"node-exporter\"})",
     "legendFormat": "RAM Cache + Buffer"
    }
   ]
  },
  {
   "title": "Memory Basic - Quario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=\"192.168.2.3:9100\",job=\"node-exporter\"} - node_memory_MemFree_bytes{instance=\"192.168.2.3:9100\",job=\"node-exporter\"} - (node_memory_Cached_bytes{instance=\"192.168.2.3:9100\",job=\"node-exporter\"} + node_memory_Buffers_bytes{instance=\"192.168.2.3:9100\",job=\"node-exporter\"} + node_memory_SReclaimable_bytes{instance=\"192.168.2.3:9100\",job=\"node-exporter\"}))",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "avg(node_memory_Cached_bytes{instance=\"192.168.2.3:9100\",job=\"node-exporter\"} + node_memory_Buffers_bytes{instance=\"192.168.2.3:9100\",job=\"node-exporter\"} + node_memory_SReclaimable_bytes{instance=\"192.168.2.3:9100\",job=\"node-exporter\"})",
     "legendFormat": "RAM Cache + Buffer"
    }
   ]
  },
  {
   "title": "Network Traffic Basic - Nucio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(irate(node_network_receive_bytes_total{instance=\"192.168.2.2:9100\",job=\"node-exporter\",device=\"eno1\"}[$range]))",
     "legendFormat": "rec"
    },
    {
     "expr": "avg(irate(node_network_transmit_bytes_total{instance=\"192.168.2.2:9100\",job=\"node-exporter\",device=\"eno1\"}[$range])*-1)",
     "legendFormat": "trans"
    }
   ]
  },
  {
   "title": "Network Traffic Basic - Quario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(irate(node_network_receive_bytes_total{instance=\"192.168.2.3:9100\",job=\"node-exporter\",device=\"eno1\"}[$range]))",
     "legendFormat": "rec"
    },
    {
     "expr": "avg(irate(node_network_transmit_bytes_total{instance=\"192.168.2.3:9100\",job=\"node-exporter\",device=\"eno1\"}[$range])*-1)",
     "legendFormat": "trans"
    }
   ]
  },
  {
   "title": "Disc Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg by (mountpoint) ((node_filesystem_avail_bytes{instance=\"192.168.2.2:9100\",job=\"node-exporter\",device!~'rootfs',mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{instance=\"192.168.2.2:9100\",job=\"node-exporter\",mountpoint=\"/\"})",
     "legendFormat": "nucio"
    },
    {
     "expr": "100 - avg by (mountpoint) ((node_filesystem_avail_bytes{instance=\"192.168.2.3:9100\",job=\"node-exporter\",device!~'rootfs',mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{instance=\"192.168.2.3:9100\",job=\"node-exporter\",mountpoint=\"/\"})",
     "legendFormat": "quario"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "avg(avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.2.2:9100\",job=\"node-exporter\"}[$range]) * on(chip,pod) group_left(chip_name) node_hwmon_chip_names{instance='192.168.2.2:9100',job=\"node-exporter\",chip_name=\"coretemp\"})",
     "legendFormat": "nucio"
    },
    {
     "expr": "avg(avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.2.3:9100\",job=\"node-exporter\"}[$range]) * on(chip,pod) group_left(chip_name) node_hwmon_chip_names{instance='192.168.2.3:9100',job=\"node-exporter\",chip_name=\"coretemp\"})",
     "legendFormat": "quario"
    }
   ]
  },
  { "title": "Nasio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(irate(ifHCInOctets{job=\"snmp-exporter\",ifName=\"eth0\"}[$range]))",
     "legendFormat": "rec"
    },
    {
     "expr": "avg(irate(ifHCOutOctets{job=\"snmp-exporter\",ifName=\"eth0\"}[$range])*-1)",
     "legendFormat": "trans"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100-(100/raidTotalSize*raidFreeSize))",
     "legendFormat": "Volume"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[$range])) by (container) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_rss{container!=\"\"}[$range])) by (container) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Longhorn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Volume usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( (avg by (pvc) (longhorn_volume_actual_size_bytes{}))/ (avg by (pvc) (longhorn_volume_capacity_bytes{})) ) *100  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Read Troughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": " sum(longhorn_volume_read_throughput) by (pvc)",
     "legendFormat": "{{pvc}}"
    }
   ]
  },
  {
   "title": "PVC Write Troughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(longhorn_volume_write_throughput) by (pvc)",
     "legendFormat": "{{pvc}}"
    }
   ]
  },
  {
   "title": "PVC Read IPOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(longhorn_volume_read_iops) by (pvc)",
     "legendFormat": "{{pvc}}"
    }
   ]
  },
  {
   "title": "PVC Write IPOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(longhorn_volume_write_iops) by (pvc)",
     "legendFormat": "{{pvc}}"
    }
   ]
  }
 ]
}