apiVersion: v1
data:
  data.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 4,
      "links": [],
      "panels": [
        {
          "fieldConfig": {
            "defaults": {},
            "overrides": []
          },
          "gridPos": {
            "h": 15,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "folderUID": "",
            "includeVars": false,
            "keepTime": false,
            "maxItems": 30,
            "query": "",
            "showFolderNames": true,
            "showHeadings": false,
            "showRecentlyViewed": false,
            "showSearch": false,
            "showStarred": true,
            "tags": []
          },
          "pluginVersion": "11.4.0",
          "title": "Starred Dashboards",
          "type": "dashlist"
        }
      ],
      "preload": false,
      "schemaVersion": 40,
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "browser",
      "title": "Home Dashboard",
      "uid": "de8jb4uguw1z4a",
      "version": 2,
      "weekStart": ""
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-dashboard-home
