apiVersion: v1
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://10.43.0.20:9090
        isDefault: true
        editable: false
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-datasources
