apiVersion: v1
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
        editable: false
        uid: "8rTXXfF4z"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-datasources
  namespace: default
