apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboard-cadvisor
          configMap:
            name: grafana-dashboard-cadvisor
        - name: grafana-dashboard-home
          configMap:
            name: grafana-dashboard-home
        - name: grafana-dashboard-longhorn
          configMap:
            name: grafana-dashboard-longhorn
        - name: grafana-dashboard-nodes
          configMap:
            name: grafana-dashboard-nodes
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
        - name: grafana-dashboard
          configMap:
            name: grafana-dashboard
        - name: grafana-storage
          emptyDir: {}
      containers:
        - image: grafana/grafana:latest
          imagePullPolicy: Always
          name: grafana
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "blablack"
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: grafana-password
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: "/tmp/dashboards/home.json"
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: "authentik"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              value: "y3cYoyNQj0t5LMBFuk7ZEMoVo6rEqluVXETJvev0"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: oidc_secret
                  name: grafana
            - name: GF_AUTH_GENERIC_OAUTH_SCOPES
              value: "openid profile email"
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_UR
              value: "http://192.168.2.221:9000/application/o/authorize/"
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              value: "http://192.168.2.221:9000/application/o/token/"
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              value: "http://192.168.2.221:9000/application/o/userinfo/"
            - name: GF_AUTH_SIGNOUT_REDIRECT_URL
              value: "http://192.168.2.221:9000/application/o/grafana/end-session/"
            - name: GF_AUTH_OAUTH_AUTO_LOGIN
              value: "true"
            - name: GF_SERVER_ROOT_URL
              value: "http://192.168.2.222:3000/"
          ports:
            - containerPort: 3000
              name: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /tmp/dashboards/cadvisor.json
              name: grafana-dashboard-cadvisor
              subPath: data.json
            - mountPath: /tmp/dashboards/home.json
              name: grafana-dashboard-home
              subPath: data.json
            - mountPath: /tmp/dashboards/longhorn.json
              name: grafana-dashboard-longhorn
              subPath: data.json
            - mountPath: /tmp/dashboards/nodes.json
              name: grafana-dashboard-nodes
              subPath: data.json
            - mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              name: grafana-dashboards
              subPath: dashboards.yaml
            - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              name: grafana-datasources
              subPath: datasources.yaml
            - mountPath: /var/lib/grafana
              name: grafana-storage
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: grafana
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.222
spec:
  selector:
    app: grafana
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 3000
      targetPort: http
