apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: default
  labels:
    app: nextcloud
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-pvc
          persistentVolumeClaim:
            claimName: nextcloud-pvc
        - name: nasio-nfs-pvc
          persistentVolumeClaim:
            claimName: nasio-nfs-pvc
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: "nextcloud"
            - name: POSTGRES_USER
              value: "nextcloud"
            - name: POSTGRES_PASSWORD
              value: "nextcloud"
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: nextcloud-pvc
              subPath: postgres
              mountPath: /var/lib/postgresql/data
          startupProbe:
            exec:
              command:
                - pg_isready
                - -U
                - nextcloud
                - -d
                - nextcloud
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - nextcloud
                - -d
                - nextcloud
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - nextcloud
                - -d
                - nextcloud
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 50Mi
        - image: redis:latest
          imagePullPolicy: Always
          name: redis
          resources:
            limits:
              cpu: 100m
              memory: 400Mi
            requests:
              cpu: 40m
              memory: 50Mi
        - name: nextcloud
          image: nextcloud:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: "nextcloud" 
            - name: POSTGRES_USER
              value: "nextcloud"
            - name: POSTGRES_PASSWORD
              value: "nextcloud"
            - name: POSTGRES_HOST
              value: "localhost"
            - name: NEXTCLOUD_DATA_DIR
              value: "/data/data"
            - name: REDIS_HOST
              value: "localhost"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-pvc
              subPath: "nextcloud"
              mountPath: "/var/www/html"
            - name: nasio-nfs-pvc
              subPath: "Kubernetes/NextCloud"
              mountPath: "/data"
          resources:
            requests:
              cpu: "1000m"
              memory: "2048Mi"
            limits:
              cpu: "2000m"
              memory: "4096Mi"
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: default
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.223
spec:
  externalTrafficPolicy: Local
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
