apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warracker-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 700Mi
  volumeName: pvc-807e792f-b2a4-4627-b672-994995aed7b7
