apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warracker-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 200Mi
  volumeName: pvc-807e792f-b2a4-4627-b672-994995aed7b7
