apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warracker-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-ad53ef91-5985-446c-953b-d1d6b8a2634c
