apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-fcf17249-650d-4ff4-ac1f-4248ee249139
