apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 200Mi
  volumeName: pvc-55d940db-2c94-4099-9b9e-ec82bdc539da
