apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      volumes:
        - name: home-assistant-pvc
          persistentVolumeClaim:
            claimName: home-assistant-pvc
      containers:
        - image: homeassistant/home-assistant:latest
          name: home-assistant
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: home-assistant-pvc
          startupProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: default
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.224
spec:
  externalTrafficPolicy: Local
  selector:
    app: home-assistant
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 8123
  type: LoadBalancer