apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k3dvol/home-assistant"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      volumes:
        - name: home-assistant-storage
          persistentVolumeClaim:
            claimName: home-assistant-pv-claim
      hostNetwork: true
      containers:
        - image: homeassistant/home-assistant:stable
          name: home-assistant
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: home-assistant-storage
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.2.201
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: homeassistant-svc
spec:
  selector:
    app: home-assistant
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.206
  ports:
    - port: 8123
      targetPort: 8123
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-udp
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: homeassistant-svc
spec:
  selector:
    app: home-assistant
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.206
  ports:
    - port: 1900
      protocol: UDP
      targetPort: 1900
      name: port1900-udp
    - port: 5353
      protocol: UDP
      targetPort: 5353
      name: port53-udp
  type: LoadBalancer
