apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      volumes:
        - name: home-assistant-pvc
          persistentVolumeClaim:
            claimName: home-assistant-pvc
      hostNetwork: true
      containers:
        - image: homeassistant/home-assistant:stable
          name: home-assistant
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: home-assistant-pvc
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 200Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/loadBalancerIPs: 192.168.2.206
spec:
  selector:
    app: home-assistant
  externalTrafficPolicy: Local
  ports:
    - port: 1900
      protocol: UDP
      targetPort: 1900
      name: port1900-udp
    - port: 5353
      protocol: UDP
      targetPort: 5353
      name: port53-udp
    - port: 8123
      protocol: TCP
      targetPort: 8123
      name: port8123-tcp
  type: LoadBalancer
