apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      nodeSelector:
        kubernetes.io/hostname: nucio
      volumes:
        - name: home-assistant-pvc
          persistentVolumeClaim:
            claimName: home-assistant-pvc
      hostNetwork: true
      containers:
        - image: homeassistant/home-assistant:latest
          name: home-assistant
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: home-assistant-pvc
          startupProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
