apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      volumes:
        - name: storage-localpath-pvc
          persistentVolumeClaim:
            claimName: storage-localpath-pvc
      hostNetwork: true
      containers:
        - image: homeassistant/home-assistant:stable
          name: home-assistant
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              subPath: "home-assistant"
              name: storage-localpath-pvc
      nodeSelector:
        cputype: x86
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.2.201
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: homeassistant-svc
spec:
  selector:
    app: home-assistant
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.206
  ports:
    - port: 8123
      targetPort: 8123
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-udp
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: homeassistant-svc
spec:
  selector:
    app: home-assistant
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.206
  ports:
    - port: 1900
      protocol: UDP
      targetPort: 1900
      name: port1900-udp
    - port: 5353
      protocol: UDP
      targetPort: 5353
      name: port53-udp
  type: LoadBalancer
