apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: jupyter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      volumes:
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - image: jupyter/minimal-notebook:latest
          imagePullPolicy: Always
          name: jupyter
          resources:
            limits:
              cpu: "2"
            requests:
              cpu: "1"
          volumeMounts:
            - mountPath: "/home/jovyan"
              subPath: "jupyter"
              name: storage-local-path-pvc
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: JUPYTER_PORT
              value: "8888"
            - name: GRANT_SUDO
              value: "yes"
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 0
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
      nodeSelector:
        cputype: x86
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: jupyter-svc
    metallb.universe.tf/loadBalancerIPs: 192.168.2.202
spec:
  externalTrafficPolicy: Local
  selector:
    app: jupyter
  ports:
    - port: 80
      targetPort: 8888
  type: LoadBalancer
