apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-distributor
  namespace: cert-manager
data:
  server.py: |
    import http.server

    CERT_PATH = "/certs/tls.crt"
    PORT = 8080

    class CertHandler(http.server.BaseHTTPRequestHandler):
        def do_GET(self):
            if self.path in ["/", "/blinky-ca.crt"]:
                with open(CERT_PATH, 'rb') as f:
                    data = f.read()
                self.send_response(200)
                self.send_header('Content-Type', 'application/x-pem-file')
                self.send_header('Content-Disposition', 'attachment; filename="blinky-ca.crt"')
                self.send_header('Content-Length', str(len(data)))
                self.end_headers()
                self.wfile.write(data)
            else:
                self.send_response(404)
                self.end_headers()

        def log_message(self, format, *args):
            print(f"{self.address_string()} - {format % args}")

    with http.server.HTTPServer(('', PORT), CertHandler) as server:
        print(f"Serving blinky-ca.crt on port {PORT}")
        server.serve_forever()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-distributor
  namespace: cert-manager
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: cert-distributor
  template:
    metadata:
      labels:
        app: cert-distributor
    spec:
      volumes:
        - name: script
          configMap:
            name: cert-distributor
        - name: certs
          secret:
            secretName: blinky-root-ca-secret
            items:
              - key: tls.crt
                path: tls.crt
      containers:
        - name: cert-distributor
          image: python:3-alpine
          command: ["python", "/app/server.py"]
          volumeMounts:
            - name: script
              mountPath: /app
            - name: certs
              mountPath: /certs
              readOnly: true
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 16Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cert-distributor
  namespace: cert-manager
spec:
  selector:
    app: cert-distributor
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cert-distributor
  namespace: cert-manager
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    external-dns.alpha.kubernetes.io/hostname: ca.nowhere
spec:
  ingressClassName: traefik
  rules:
    - host: ca.nowhere
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cert-distributor
                port:
                  number: 80
