apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-builder-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k3dvol/docker-builder"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-builder-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: docker-builder
spec:
  schedule: "0 0 1 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: docker-builder
        spec:
          volumes:
          - name: docker-builder-storage
            persistentVolumeClaim:
              claimName: docker-builder-pv-claim
          containers:
            - image: nucio.nowhere:30038/docker-builder:latest
              name: docker-builder
              volumeMounts:
              - mountPath: "/data"
                name: docker-builder-storage
              imagePullPolicy: Always
              securityContext:
                privileged: true
          restartPolicy: Never
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 192.168.2.200
