apiVersion: batch/v1
kind: CronJob
metadata:
  name: docker-builder
spec:
  schedule: "0 0 1 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: docker-builder
        spec:
          volumes:
            - name: docker-builder-storage
              persistentVolumeClaim:
                claimName: config-pv-claim
          containers:
            - image: nucio.nowhere:30038/docker-builder:latest
              name: docker-builder
              volumeMounts:
                - mountPath: "/data"
                  subPath: "docker-builder"
                  name: docker-builder-storage
              imagePullPolicy: Always
              securityContext:
                privileged: true
          restartPolicy: Never
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 192.168.2.201
