apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer-editor
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: homer-editor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homer-editor
        part-of: homer
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "part-of"
                    operator: In
                    values:
                      - homer
              topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: homer-pvc
          persistentVolumeClaim:
            claimName: homer-pvc
      containers:
        - image: linuxserver/code-server
          imagePullPolicy: Always
          name: homer-editor
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "EU/Dublin"
          volumeMounts:
            - mountPath: "/homer-config"
              subPath: "homer"
              name: homer-pvc
            - mountPath: "/config"
              subPath: "editor"
              name: homer-pvc
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: homer-editor
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: homer-shared-ip
    metallb.universe.tf/loadBalancerIPs: 192.168.2.218
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: homer-editor
  ports:
    - port: 8443
      targetPort: 8443
  type: LoadBalancer
