apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: homer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homer
        part-of: homer
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "part-of"
                    operator: In
                    values:
                      - homer
              topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: homer-pvc
          persistentVolumeClaim:
            claimName: homer-pvc
      containers:
        - image: b4bz/homer:latest
          imagePullPolicy: Always
          name: homer
          volumeMounts:
            - mountPath: "/www/assets"
              subPath: "homer"
              name: homer-pvc
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      initContainers:
        - image: alpine:latest
          imagePullPolicy: Always
          name: init-assets-folder
          command: ["chown"]
          args: ["1000:1000", "/www/assets"]
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/www/assets"
              subPath: "homer"
              name: homer-pvc
          resources:
            limits:
              cpu: 20m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: homer
  annotations:
    metallb.io/address-pool: default
    metallb.io/allow-shared-ip: homer-shared-ip
    metallb.io/loadBalancerIPs: 192.168.2.200
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: homer
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: homer-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: homer
  updatePolicy:
    updateMode: "Auto"
