apiVersion: apps/v1
kind: Deployment
metadata:
  name: nordvpn-meshnet
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nordvpn-meshnet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nordvpn-meshnet
    spec:
      containers:
        - image: nucio.nowhere:30038/nordvpn:latest
          imagePullPolicy: Always
          name: nordvpn
          lifecycle:
            postStart:
              exec:
                command:
                  ["/bin/sh", "-c", "/wait_for_nordvpn.sh > /usr/share/message"]
          env:
            - name: NORDVPN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nordvpn-token
                  key: password
            - name: COUNTRY
              value: "IRELAND"
            - name: NETWORK
              value: "192.168.2.0/24"
            - name: DNS
              value: "192.168.2.201"
            - name: MESHNET
              value: "True"
            - name: DEBUG
              value: "True"
          livenessProbe:
            exec:
              command:
                - /check_nordvpn_connection.sh
            initialDelaySeconds: 30
            periodSeconds: 600
            timeoutSeconds: 30
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
      nodeSelector:
        cputype: x86
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
