apiVersion: v1
kind: PersistentVolume
metadata:
  name: vikunja-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k3dvol/vikunja"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k3dvol/mariadb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
      containers:
        - image: mariadb
          imagePullPolicy: Always
          name: mariadb
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mariadb-storage
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-password
                  key: password
            - name: MYSQL_USER
              value: vikunja
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-password
                  key: password
            - name: MYSQL_DATABASE
              value: vikunja
            - name: TZ
              value: "EU/Dublin"
          ports:
            - containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja-backend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: vikunja-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vikunja-backend
    spec:
      volumes:
        - name: vikunja-storage
          persistentVolumeClaim:
            claimName: vikunja-pv-claim
      containers:
        - image: vikunja/api
          imagePullPolicy: Always
          name: vikunja-backend
          ports:
            - containerPort: 3456
          volumeMounts:
            - mountPath: "/app/vikunja/files"
              name: vikunja-storage
          env:
            - name: VIKUNJA_DATABASE_HOST
              value: mariadb
            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-password
                  key: password
            - name: VIKUNJA_DATABASE_TYPE
              value: mysql
            - name: VIKUNJA_DATABASE_USER
              value: vikunja
            - name: VIKUNJA_DATABASE_DATABASE
              value: vikunja
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: vikunja-frontend
  template:
    metadata:
      labels:
        app: vikunja-frontend
    spec:
      containers:
        - name: vikunja-frontend
          image: vikunja/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VIKUNJA_API_URL
              value: "http://192.168.2.207:3456/api/v1"
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vikunja-frontend
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: vikunja-svc
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.2.207
  selector:
    app: vikunja-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: vikunja-backend
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: vikunja-svc
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.2.207
  selector:
    app: vikunja-backend
  ports:
    - port: 3456
      targetPort: 3456
  type: LoadBalancer
