apiVersion: v1
kind: Service
metadata:
  name: argocd
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    name: blinky-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - argocd.nowhere
  privateKey:
    rotationPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.alpha.kubernetes.io/hostname: argocd.nowhere
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - argocd.nowhere
      secretName: argocd-tls
  rules:
    - host: argocd.nowhere
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd
                port:
                  number: 80
