apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-namespace.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=stable
  - argocd-service.yaml
  - argocd-applicationset.yaml
  - argocd-config.yaml

patches:
  - path: patches/argocd-dex-patch.yaml
    target:
      kind: Deployment
      name: argocd-dex-server
  - path: argocd-dex-config.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
