apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=stable

patches:
- path: patches/argocd-dex-patch.yaml
  target:
    kind: Deployment
    name: argocd-dex-server