apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: unbound
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unbound
    spec:
      volumes:
        - name: unbound-storage
          persistentVolumeClaim:
            claimName: config-pv-claim
      containers:
        - image: mvance/unbound:latest
          imagePullPolicy: Always
          name: unbound
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/opt/unbound/etc/unbound/"
              subPath: "unbound"
              name: unbound-storage
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.2.201
---
apiVersion: v1
kind: Service
metadata:
  name: unbound
spec:
  selector:
    app: unbound
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.202
  ports:
    - protocol: TCP
      port: 5335
      targetPort: 53
      name: tcpport
    - protocol: UDP
      port: 5335
      targetPort: 53
      name: udpport
  type: LoadBalancer
