apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: tailscale
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: tailscale
      containers:
        - name: tailscale
          image: tailscale/tailscale:latest
          imagePullPolicy: Always
          env:
            - name: TS_HOSTNAME
              value: "blinky"
            - name: TS_ENABLE_HEALTH_CHECK
              value: "true"
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: TS_AUTHKEY
            - name: TS_ROUTES
              value: "10.42.0.0/16,10.43.0.0/16,192.168.2.0/24"
            - name: TS_KUBE_SECRET
              value: "tailscale-state"  
            - name: TS_EXTRA_ARGS
              value: "--advertise-exit-node --accept-dns --advertise-connector"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 100Mi
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: tailscale-pvc
              mountPath: /var/lib/tailscale
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        - name: tailscale-pvc
          persistentVolumeClaim:
            claimName: tailscale-pvc

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
    resourceNames: ["tailscale"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch"]
    resourceNames: ["tailscale-state"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale
subjects:
  - kind: ServiceAccount
    name: tailscale
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tailscale
subjects:
  - kind: ServiceAccount
    name: tailscale
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: tailscale
  namespace: default
spec:
  selector:
    app: tailscale  
  ports:
  - name: health
    port: 9002
    targetPort: 9002
  type: ClusterIP