apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restarter-nordvpn-meshnet
  namespace: default
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  schedule: "0 0 1 */6 *"
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: deployment-restarter
          restartPolicy: Never
          containers:
            - name: deployment-restarter-nordvpn-meshnet
              image: bitnami/kubectl
              command:
                - bash
                - -c
                - >-
                  kubectl rollout restart deployment/nordvpn-meshnet &&
                  kubectl rollout status deployment/nordvpn-meshnet
