apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-system-config-pv-volume
  labels:
    type: local
  namespace: kube-system
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k3dvol"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pv-claim
  namespace: kube-system
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi