apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-longhorn
provisioner: driver.longhorn.io
parameters:
  dataLocality: disabled
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
