apiVersion: v1
kind: PersistentVolume
metadata:
  name: nasio-nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
    - rsize=4096
    - wsize=4096
    - noacl
    - nocto
    - noatime
    - nodiratime
    - async
  nfs:
    path: /volume1/public
    server: 192.168.2.4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nasio-nfs-pvc
spec:
  storageClassName: nfs
  volumeName: nasio-nfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
