apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
    - rsize=4096
    - wsize=4096
    - noacl
    - nocto
    - noatime
    - nodiratime
  nfs:
    path: /volume1/public
    server: 192.168.2.3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-claim
spec:
  storageClassName: nfs
  volumeName: nfs-pv-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
