apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-local-path-default-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/nfs/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-local-path-pvc
  namespace: default
spec:
  storageClassName: local-path
  volumeName: nfs-local-path-default-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-local-path-kube-system-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/nfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-local-path-pvc
  namespace: kube-system
spec:
  storageClassName: local-path
  volumeName: nfs-local-path-kube-system-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
