apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
    - rsize=4096
    - wsize=4096
    - noacl
    - nocto
    - noatime
    - nodiratime
    - async
  nfs:
    path: /
    server: 10.43.0.21
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nfs-pvc
spec:
  storageClassName: nfs
  volumeName: nfs-nfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
