apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-local-path-default-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k3dvol/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-local-path-pvc
  namespace: default
spec:
  storageClassName: local-path
  volumeName: storage-local-path-default-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-local-path-kube-system-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k3dvol"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-local-path-pvc
  namespace: kube-system
spec:
  storageClassName: local-path
  volumeName: storage-local-path-kube-system-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
