apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: node-red
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-red
    spec:
      volumes:
        - name: node-red-pvc
          persistentVolumeClaim:
            claimName: node-red-pvc
      containers:
        - image: nodered/node-red:latest
          imagePullPolicy: Always
          name: node-red
          volumeMounts:
            - mountPath: "/data"
              name: node-red-pvc
          env:
            - name: NODE_RED_ENABLE_PROJECTS
              value: "true"
            - name: TZ
              value: "Europe/Dublin"
          startupProbe:
            httpGet:
              path: /
              port: 1880
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 1880
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 1880
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 100Mi
      initContainers:
        - image: alpine:latest
          imagePullPolicy: Always
          name: init-assets-folder
          command: ["chmod"]
          args: ["777", "/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/data"
              name: node-red-pvc
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: node-red
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.205
spec:
  externalTrafficPolicy: Local
  selector:
    app: node-red
  ports:
    - port: 80
      targetPort: 1880
  type: LoadBalancer
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: node-red-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: node-red
  updatePolicy:
    updateMode: "Auto"
