apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: localai
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: localai
    spec:
      volumes:
        - name: nasio-nfs-pvc
          persistentVolumeClaim:
            claimName: nasio-nfs-pvc
      containers:
        - image: localai/localai:latest-aio-cpu
          imagePullPolicy: Always
          name: localai
          volumeMounts:
            - mountPath: "/build/models"
              subPath: "Kubernetes/localai"
              name: nasio-nfs-pvc
          resources:
            limits:
              cpu: 3000m
              memory: 24Gi
            requests:
              cpu: 200m
              memory: 2000Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: localai
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/loadBalancerIPs: 192.168.2.219
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: localai
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
