apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 200Mi
  volumeName: pvc-2057574c-d9b2-40b2-b6c0-9dfe37a4b192
