apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 200Mi
  volumeName: pvc-8c69ef7c-1e40-4744-a14b-05e606e4baf9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 200Mi
  volumeName: pvc-4f5110ac-adf0-4f20-b6c3-12b3efe3642c