- name: Setup network
  hosts: lumio
  become: true

  tasks:
    - name: Disable cloud network config
      ansible.builtin.copy:
        src: all/99-disable-network-config.cfg
        dest: /etc/cloud/cloud.cfg.d/
    - name: Empty /etc/netplan
      ansible.builtin.shell:
        cmd: rm -rf /etc/netplan/*

- name: Setup APT
  hosts: lumio
  become: true

  tasks:
    - name: Disable phased updates
      ansible.builtin.copy:
        src: all/99-phased-updates
        dest: /etc/apt/apt.conf.d/

- name: Setup network on Lumio
  hosts: lumio
  become: true

  tasks:
    - name: Copy Netplan configuration
      ansible.builtin.template:
        src: lumio/00-myconfig.yaml.j2
        dest: /etc/netplan/00-myconfig.yaml
        mode: '0600'

- name: Setup network
  hosts: lumio
  become: true

  tasks:
    - name: Setup ipv6
      ansible.builtin.copy:
        src: all/sysctl.conf
        dest: /etc/
    - name: Copy resolved.conf
      ansible.builtin.copy:
        src: all/resolved.conf
        dest: /etc/systemd/
    - name: Create symlink
      ansible.builtin.shell:
        cmd: ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf

- name: Install basic packages
  hosts: lumio
  become: true

  tasks:
    - name: Install package
      ansible.builtin.apt:
        pkg:
          - nano
          - htop
          - bash-completion

- name: Install intel packages
  hosts: lumio
  become: true

  tasks:
    - name: Install package
      ansible.builtin.apt:
        pkg:
          - intel-media-va-driver-non-free
          - intel-gpu-tools

- name: Configure login info
  hosts: lumio
  become: true

  tasks:
    - name: Remove packages
      ansible.builtin.apt:
        pkg:
          - ubuntu-advantage-tools
        state: absent

    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - landscape-common
          - update-notifier-common

    - name: Remove unminimize message
      ansible.builtin.file:
        state: absent
        path: /etc/update-motd.d/60-unminimize

- name: Setup timezone
  hosts: lumio
  become: true

  tasks:
    - name: timedatectl
      ansible.builtin.shell:
        cmd: timedatectl set-timezone Europe/Dublin

- name: Remove snapd
  hosts: lumio
  become: true

  tasks:
    - name: Check if snap binary present
      stat:
        path: "/usr/bin/snap"
      register: snap_exist

    - name: Debug if snap installed
      debug:
        msg: "snap is installed"
      when: snap_exist.stat.exists

    - name: Check if packages are present
      ansible.builtin.shell:
        cmd: snap list
      register: snap_output
      when: snap_exist.stat.exists

    - name: Debug snap list
      debug:
        msg: "{{snap_output}}"
      when: snap_exist.stat.exists

    - name: Debug uninstall snap packages
      debug:
        msg: "Will uninstall packages"
      when:
        - snap_exist.stat.exists
        - snap_output is defined
        - '"No snaps are installed yet" not in snap_output.stderr'

    - name: Uninstall snap packages
      ansible.builtin.shell:
        cmd: snap remove --purge $(snap list | awk '!/^Name|^core/ {print $1}')
      when:
        - snap_exist.stat.exists
        - snap_output is defined
        - '"No snaps are installed yet" not in snap_output.stderr'

    - name: Remove snapd
      ansible.builtin.apt:
        name: snapd
        state: absent

- name: Remove packages
  hosts: lumio
  become: true

  tasks:
    - name: Remove ModemManager
      ansible.builtin.apt:
        name: modemmanager
        state: absent

- name: Cleanup
  hosts: lumio
  become: true

  tasks:
    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes

- name: Reboot all machines
  hosts: lumio
  become: true

  tasks:
    - name: Reboot
      ansible.builtin.reboot:


