apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: overseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      volumes:
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
      containers:
        - image: linuxserver/overseerr:latest
          imagePullPolicy: Always
          name: overseerr
          volumeMounts:
            - mountPath: "/config"
              subPath: "overseerr"
              name: storage-local-path-pvc
          env:
            - name: TZ
              value: "Europe/Dublin"
      nodeSelector:
        cputype: x86
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: overseerr-svc
    metallb.universe.tf/loadBalancerIPs: 192.168.2.214
spec:
  externalTrafficPolicy: Local
  selector:
    app: overseerr
  ports:
    - port: 80
      targetPort: 5055
  type: LoadBalancer
