apiVersion: batch/v1
kind: CronJob
metadata:
  name: kublicity-full
spec:
  schedule: "0 0 16 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kublicity
        spec:
          volumes:
            - name: cluster-config
              persistentVolumeClaim:
                claimName: config-pv-claim
            - name: kublicity-nfs
              persistentVolumeClaim:
                claimName: nfs-pv-claim
          containers:
            - image: nucio.nowhere:30038/kublicity:latest
              imagePullPolicy: Always
              command: ["duplicity"]
              args:
                [
                  "full",
                  "/data",
                  "file:///backup/DejaDupNucio",
                  "--no-encryption",
                  "--allow-source-mismatch",
                ]
              name: kublicity-full
              volumeMounts:
                - mountPath: "/data"
                  name: cluster-config
                - mountPath: "/backup"
                  subPath: "MyBackup"
                  name: kublicity-nfs
                - mountPath: "/root"
                  subPath: "kublicity"
                  name: cluster-config
          restartPolicy: Never
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 192.168.2.201
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kublicity-clean
spec:
  schedule: "0 4 1 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kublicity
        spec:
          volumes:
            - name: cluster-config
              persistentVolumeClaim:
                claimName: config-pv-claim
            - name: kublicity-nfs
              persistentVolumeClaim:
                claimName: nfs-pv-claim
          containers:
            - image: nucio.nowhere:30038/kublicity:latest
              imagePullPolicy: Always
              command: ["duplicity"]
              args:
                [
                  "remove-all-but-n-full",
                  "3",
                  "file:///backup/DejaDupNucio",
                  "--force",
                ]
              name: kublicity-clean
              volumeMounts:
                - mountPath: "/data"
                  name: cluster-config
                - mountPath: "/backup"
                  subPath: "MyBackup"
                  name: kublicity-nfs
                - mountPath: "/root"
                  subPath: "kublicity"
                  name: cluster-config
          restartPolicy: Never
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 192.168.2.201
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kublicity-incr
spec:
  schedule: "0 2 * * 0"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kublicity
        spec:
          volumes:
            - name: cluster-config
              persistentVolumeClaim:
                claimName: config-pv-claim
            - name: kublicity-nfs
              persistentVolumeClaim:
                claimName: nfs-pv-claim
          containers:
            - image: nucio.nowhere:30038/kublicity:latest
              imagePullPolicy: Always
              command: ["duplicity"]
              args:
                [
                  "incr",
                  "/data",
                  "file:///backup/DejaDupNucio",
                  "--no-encryption",
                  "--allow-source-mismatch",
                ]
              name: kublicity-incr
              volumeMounts:
                - mountPath: "/data"
                  name: cluster-config
                - mountPath: "/backup"
                  subPath: "MyBackup"
                  name: kublicity-nfs
                - mountPath: "/root"
                  subPath: "kublicity"
                  name: cluster-config
          restartPolicy: Never
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 192.168.2.201
