apiVersion: batch/v1
kind: CronJob
metadata:
  name: kublicity-full-nucio
spec:
  schedule: "0 0 16 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: kublicity
        spec:
          volumes:
            - name: storage-localpath-pvc
              persistentVolumeClaim:
                claimName: storage-localpath-pvc
            - name: nasio-nfs-pvc
              persistentVolumeClaim:
                claimName: nasio-nfs-pvc
          containers:
            - image: nucio.nowhere:30038/kublicity:latest
              imagePullPolicy: Always
              command: ["duplicity"]
              args:
                [
                  "full",
                  "/data",
                  "file:///backup/DejaDupNucio",
                  "--no-encryption",
                  "--allow-source-mismatch",
                ]
              name: kublicity-full-nucio
              volumeMounts:
                - mountPath: "/data"
                  name: storage-localpath-pvc
                - mountPath: "/backup"
                  subPath: "MyBackup"
                  name: nasio-nfs-pvc
                - mountPath: "/root"
                  subPath: "kublicity"
                  name: storage-localpath-pvc
          nodeSelector:
            cputype: x86
          restartPolicy: Never
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 192.168.2.201
