apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: uptime-kuma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      volumes:
        - name: uptime-kuma-pvc
          persistentVolumeClaim:
            claimName: uptime-kuma-pvc
      containers:
        - image: louislam/uptime-kuma:latest
          imagePullPolicy: Always
          name: uptime-kuma
          ports:
            - containerPort: 3001
              name: uptime-kuma-tcp
              protocol: TCP
          volumeMounts:
            - mountPath: "/app/data"
              name: uptime-kuma-pvc
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 400m
              memory: 250Mi
            requests:
              cpu: 200m
              memory: 100Mi
        - image: nucio.nowhere:30038/uptime-kuma-api:latest
          imagePullPolicy: Always
          name: uptime-kuma-api
          ports:
            - containerPort: 8000
              name: kuma-api-tcp
              protocol: TCP
          env:
            - name: KUMA_URL
              value: "http://localhost:3001"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: uptime-kuma-credentials
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uptime-kuma-credentials
                  key: password
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  annotations:
    metallb.io/address-pool: default
    metallb.io/allow-shared-ip: uptime-kuma-shared-ip
    metallb.io/loadBalancerIPs: 192.168.2.219
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: uptime-kuma
  ports:
    - port: 80
      targetPort: 3001
      name: "ui-port"
    - port: 8000
      targetPort: 8000
      name: "api-port"
  type: LoadBalancer
