apiVersion: batch/v1
kind: CronJob
metadata:
  name: build-dnsmasq
spec:
  schedule: "0 0 6 */6 *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: build-dnsmasq
        spec:
          containers:
            - image: nucio.nowhere:30038/docker-builder:latest
              name: build-dnsmasq
              imagePullPolicy: Always
              command: ["./build.sh"]
              args: ["dnsmasq", "linux/amd64"]
              securityContext:
                privileged: true
              resources:
                limits:
                  cpu: 200m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
          restartPolicy: Never
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 10.43.0.22
