apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-yvonne-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 1Gi
