apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-aurelien-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-4945cfc3-a14d-4902-a313-20b18a8b1b94
