apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-yvonne-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 200Mi
  volumeName: pvc-3272a4c4-577d-486a-a143-27e8abd0c376
