apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing-yvonne
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: syncthing-yvonne
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syncthing-yvonne
    spec:
      volumes:
        - name: nasio-nfs-pvc
          persistentVolumeClaim:
            claimName: nasio-nfs-pvc
        - name: syncthing-yvonne-pvc
          persistentVolumeClaim:
            claimName: syncthing-yvonne-pvc
      containers:
        - image: syncthing/syncthing:latest
          imagePullPolicy: Always
          name: syncthing-yvonne
          volumeMounts:
            - mountPath: "/nasio"
              name: nasio-nfs-pvc
            - mountPath: "/var/syncthing"
              name: syncthing-yvonne-pvc
          env:
            - name: PUID
              value: "1027"
            - name: PGID
              value: "100"
          startupProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          ports:
            - containerPort: 8384
              name: web-ui
              protocol: TCP
            - containerPort: 22000
              name: syncthing-tcp
              protocol: TCP
            - containerPort: 22000
              name: syncthing-udp
              protocol: UDP
          resources:
            limits:
              cpu: 200m
              memory: 750Mi
            requests:
              cpu: 10m
              memory: 50Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-yvonne
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.212
spec:
  externalTrafficPolicy: Local
  selector:
    app: syncthing-yvonne
  ports:
    - port: 8384
      targetPort: 8384
      name: web-ui
      protocol: TCP
    - port: 22000
      targetPort: 22000
      name: syncthing-tcp
      protocol: TCP
    - port: 22000
      targetPort: 22000
      name: syncthing-udp
      protocol: UDP
  type: LoadBalancer
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: syncthing-yvonne-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: syncthing-yvonne
  updatePolicy:
    updateMode: "Auto"
