apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing-aurelien
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: syncthing-aurelien
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syncthing-aurelien
    spec:
      volumes:
        - name: nasio-nfs-pvc
          persistentVolumeClaim:
            claimName: nasio-nfs-pvc
        - name: syncthing-aurelien-pvc
          persistentVolumeClaim:
            claimName: syncthing-aurelien-pvc
      containers:
        - image: syncthing/syncthing:latest
          imagePullPolicy: Always
          name: syncthing-aurelien
          volumeMounts:
            - mountPath: "/nasio"
              name: nasio-nfs-pvc
            - mountPath: "/var/syncthing"
              name: syncthing-aurelien-pvc
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
          startupProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          ports:
            - containerPort: 8384
              name: web-ui
              protocol: TCP
            - containerPort: 22000
              name: syncthing-tcp
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 750Mi
            requests:
              cpu: 50m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-aurelien-sync-tcp
  namespace: default
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.222
    metallb.io/allow-shared-ip: syncthing-aurelien-sync
spec:
  externalTrafficPolicy: Local
  selector:
    app: syncthing-aurelien
  ports:
    - port: 22000
      targetPort: 22000
      name: syncthing-tcp
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-aurelien-sync-udp
  namespace: default
  annotations:
    metallb.io/address-pool: default
    metallb.io/loadBalancerIPs: 192.168.2.222
    metallb.io/allow-shared-ip: syncthing-aurelien-sync
spec:
  externalTrafficPolicy: Local
  selector:
    app: syncthing-aurelien
  ports:
    - port: 22000
      targetPort: 22000
      name: syncthing-udp
      protocol: UDP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-aurelien
  namespace: default
spec:
  selector:
    app: syncthing-aurelien
  ports:
    - port: 8384
      targetPort: 8384
      name: web-ui
      protocol: TCP
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: syncthing-aurelien-tls
  namespace: default
spec:
  secretName: syncthing-aurelien-tls
  issuerRef:
    name: blinky-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - syncthing-aurelien.nowhere
  privateKey:
    rotationPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing-aurelien
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.alpha.kubernetes.io/hostname: syncthing-aurelien.nowhere
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - syncthing-aurelien.nowhere
      secretName: syncthing-aurelien-tls
  rules:
    - host: syncthing-aurelien.nowhere
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: syncthing-aurelien
                port:
                  number: 8384
