apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing-aurelien
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: syncthing-aurelien
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syncthing-aurelien
    spec:
      volumes:
        - name: nasio-nfs-pvc
          persistentVolumeClaim:
            claimName: nasio-nfs-pvc
        - name: syncthing-aurelien-pvc
          persistentVolumeClaim:
            claimName: syncthing-aurelien-pvc
      containers:
        - image: syncthing/syncthing:latest
          imagePullPolicy: Always
          name: syncthing-aurelien
          volumeMounts:
            - mountPath: "/nasio"
              name: nasio-nfs-pvc
            - mountPath: "/var/syncthing"
              name: syncthing-aurelien-pvc
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
          ports:
            - containerPort: 8384
              name: web-ui
              protocol: TCP
            - containerPort: 22000
              name: syncthing-tcp
              protocol: TCP
            - containerPort: 22000
              name: syncthing-udp
              protocol: UDP
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-aurelien
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/loadBalancerIPs: 192.168.2.211
spec:
  externalTrafficPolicy: Local
  selector:
    app: syncthing-aurelien
  ports:
    - port: 8384
      targetPort: 8384
      name: web-ui
      protocol: TCP
    - port: 22000
      targetPort: 22000
      name: syncthing-tcp
      protocol: TCP
    - port: 22000
      targetPort: 22000
      name: syncthing-udp
      protocol: UDP
  type: LoadBalancer
