apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing-yvonne
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: syncthing-yvonne
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syncthing-yvonne
    spec:
      volumes:
        - name: nasio-nfs-pvc
          persistentVolumeClaim:
            claimName: nasio-nfs-pvc
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
      containers:
        - image: syncthing/syncthing
          imagePullPolicy: Always
          name: syncthing-yvonne
          volumeMounts:
            - mountPath: "/nasio"
              name: nasio-nfs-pvc
            - mountPath: "/var/syncthing"
              subPath: "syncthing/yvonne"
              name: storage-local-path-pvc
          env:
            - name: PUID
              value: "1027"
            - name: PGID
              value: "100"
          ports:
            - containerPort: 8384
              name: web-ui
              protocol: TCP
            - containerPort: 22000
              name: syncthing-tcp
              protocol: TCP
            - containerPort: 22000
              name: syncthing-udp
              protocol: UDP
      nodeSelector:
        cputype: x86
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-yvonne
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: syncthing-yvonne-svc
    metallb.universe.tf/loadBalancerIPs: 192.168.2.212
spec:
  externalTrafficPolicy: Local
  selector:
    app: syncthing-yvonne
  ports:
    - port: 8384
      targetPort: 8384
      name: web-ui
      protocol: TCP
    - port: 22000
      targetPort: 22000
      name: syncthing-tcp
      protocol: TCP
    - port: 22000
      targetPort: 22000
      name: syncthing-udp
      protocol: UDP
  type: LoadBalancer
