apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-yvonne-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-048e43cc-9739-4305-a9c4-925369340b78
