apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-aurelien-pvc
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-longhorn
  resources:
    requests:
      storage: 200Mi
  volumeName: pvc-44fe333b-8dc6-4206-8a19-40912351a3b8
