apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrent-vpn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: torrent-vpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: torrent-vpn
    spec:
      volumes:
        - name: storage-local-path-pvc
          persistentVolumeClaim:
            claimName: storage-local-path-pvc
        - name: nasio-nfs-pvc
          persistentVolumeClaim:
            claimName: nasio-nfs-pvc
      containers:
        - image: nucio.nowhere:30038/nordvpn:latest
          imagePullPolicy: Always
          name: nordvpn
          lifecycle:
            postStart:
              exec:
                command:
                  ["/bin/sh", "-c", "/wait_for_nordvpn.sh > /usr/share/message"]
          env:
            - name: NORDVPN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nordvpn-token
                  key: password
            - name: COUNTRY
              value: "P2P"
            - name: NETWORK
              value: "192.168.2.0/24"
            - name: PORTS
              value: "8112,6881,8080"
            - name: DNS
              value: "192.168.2.201"
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
        - image: linuxserver/qbittorrent:latest
          imagePullPolicy: Always
          name: qbittorrent
          ports:
            - containerPort: 8112
              protocol: TCP
            - containerPort: 6881
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
          volumeMounts:
            - mountPath: "/config"
              subPath: "qbittorrent"
              name: storage-local-path-pvc
            - mountPath: "/volume1/public/Torrent Downloads"
              subPath: "Torrent Downloads"
              name: nasio-nfs-pvc
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
            - name: WEBUI_PORT
              value: "8112"
        - image: linuxserver/prowlarr:latest
          imagePullPolicy: Always
          name: prowlarr
          volumeMounts:
            - mountPath: "/config"
              subPath: "prowlarr"
              name: storage-local-path-pvc
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "EU/Dublin"
      nodeSelector:
        cputype: x86
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: torrent-vpn
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: torrent-vpn-svc
    metallb.universe.tf/loadBalancerIPs: 192.168.2.207
spec:
  externalTrafficPolicy: Local
  selector:
    app: torrent-vpn
  ports:
    - port: 8112
      targetPort: 8112
      name: qbittorrent-web
    - port: 80
      targetPort: 9696
      name: prowlarr-web
  type: LoadBalancer
