apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: flaresolverr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - image: flaresolverr/flaresolverr:latest
          imagePullPolicy: Always
          name: flaresolverr
          env:
            - name: TZ
              value: "EU/Dublin"
            - name: LANG
              value: "en_GB"
            - name: BROWSER_TIMEOUT
              value: "180000"
          resources:
            limits:
              cpu: 1000m
              memory: 750Mi
            requests:
              cpu: 50m
              memory: 100Mi
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.22
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-internal
spec:
  clusterIP: 10.43.0.24
  ports:
    - port: 8191
      targetPort: 8191
      name: port8191
      protocol: TCP
  selector:
    app: flaresolverr
  type: ClusterIP
