---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: picsync-immich
spec:
  schedule: "0 0 15 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: picsync-immich
        spec:
          volumes:
            - name: nasio-nfs-pvc
              persistentVolumeClaim:
                claimName: nasio-nfs-pvc
          containers:
            - image: nucio.nowhere:30038/picsync:latest
              imagePullPolicy: Always
              env:
                - name: SSHPASS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: picsync-sshpassword
                      key: password
                - name: NTFY_URL
                  value: "192.168.2.220"
              command: ["python3"]
              args:
                [
                  "picsync.py",
                  "-h",
                  "igorito.nowhere",
                  "-u",
                  "blablack",
                  "-s",
                  "/source/",
                  "-t",
                  "~/Pictures Backup/Our Pictures - Immich",
                ]
              name: picsync
              volumeMounts:
                - mountPath: "/source"
                  subPath: "Kubernetes/Our Pictures - Immich/library"
                  name: nasio-nfs-pvc
              resources:
                limits:
                  cpu: 200m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
          restartPolicy: Never
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 10.43.0.22
