---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: picsync
spec:
  schedule: "0 0 15 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: picsync
        spec:
          volumes:
            - name: picsync-nfs
              persistentVolumeClaim:
                claimName: nfs-pv-claim
          containers:
            - image: nucio.nowhere:30038/picsync:latest
              imagePullPolicy: Always
              env:
                - name: SSHPASS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: picsync-sshpassword
                      key: password
              command: ["python3"]
              args:
                [
                  "picsync.py",
                  "-h",
                  "igorito.nowhere",
                  "-u",
                  "blablack",
                  "-s",
                  "/source/",
                  "-t",
                  "~/Pictures",
                ]
              name: picsync
              volumeMounts:
                - mountPath: "/source"
                  subPath: "Our Pictures"
                  name: picsync-nfs
          nodeSelector:
            cputype: x86
          restartPolicy: Never
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 192.168.2.201
