apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
spec:
  template:
    spec:
      containers:
        - name: intel-gpu-plugin
          image: intel/intel-gpu-plugin:0.32.1
          imagePullPolicy: Always
          args:
            - "-shared-dev-num"
            - "2"
