apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
spec:
  template:
    spec:
      containers:
      - name: intel-gpu-plugin
        imagePullPolicy: Always
        args:
        - "-shared-dev-num"
        - "2"