apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/intel/intel-device-plugins-for-kubernetes/refs/heads/main/deployments/gpu_plugin/base/intel-gpu-plugin.yaml

patches:
- path: intel-gpu-plugin-patch.yaml
  target:
    kind: DaemonSet
    name: intel-gpu-plugin