apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-bootstrap
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blinky-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: blinky-root-ca
  secretName: blinky-root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Never
  issuerRef:
    name: selfsigned-bootstrap
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: blinky-ca-issuer
spec:
  ca:
    secretName: blinky-root-ca-secret
